<div data-dojo-type="dijit.Dialog" data-dojo-id="confirm" id="confirm" data-dojo-props="title:'Cache Cleared'">
    <div class="dijitDialogPaneContentArea">
        <div>
            <p>
                The DataBase Cache has been cleared successfully 
            </p>
        </div>
        <button data-dojo-type="dijit.form.Button">
            Close
            <script type="dojo/method" data-dojo-event="onClick">
                return bba.closeDialog(confirm);
            </script>
        </button>
    </div>
</div>