<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Client Addresses',
    'label'     => 'New Address',
    'location'  => $this->url(array(
        'controller'    => 'client-address',
        'action'        => 'add',
        'clientId'      => $this->idClient
    ), 'default', true)
)); ?>

<div dojoType="dojox.data.QueryReadStore"
     jsid="clientAddressStore"
     url="/client-address/client-address-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="addressGrid"
       store="clientAddressStore"
       query="{ id: <?php echo $this->idClient; ?> }"
       style="margin:auto;"
       autoWidth="true"
       autoHeight="20"
       selectionMode="single"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>This Client has no addresses yet.</span>">
    <thead>
        <tr>
            <th field="clientAd_idAddress" width="75">Id</th>
            <th field="clientAd_addressName" width="250">Address Name</th>
            <th field="clientAd_address1" width="300">Address 1</th>
            <th field="clientAd_address2" width="200">Address 2</th>
            <th field="clientAd_address3" width="100">Address 3</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>
