<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Client Contacts',
    'label'     => 'New Contact',
    'location'  => $this->url(array(
        'controller'    => 'client-contact',
        'action'        => 'add',
        'clientId'      => $this->idClient
    ), 'default', true)
)); ?>

<table>
    <tr>
        <th>Name <span class="id">(id)</span></th>
        <th>Type</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Postcode</th>
        <th>&nbsp;</th>
    </tr>
<?php if ($this->contacts): ?>
	<?php foreach($this->contacts as $contact): ?>
		<tr>
			<td><?php echo $this->escape($contact->name); ?>&nbsp;
				<span class="id">(<?php echo $this->escape($contact->idClientContact); ?>)</span></td>
			<td><?php echo $this->escape($contact->type); ?></td>
			<td><?php echo $this->escape($contact->phone); ?></td>
			<td><?php echo $this->escape($contact->email); ?></td>
			<td><?php echo $this->escape($contact->postcode); ?></td>
			<td class="action">
                <button dojoType="dijit.form.Button" type="button">
                    Edit
                    <script type="dojo/method" event="onClick" args="evt">
                        location.href = "<?php echo $this->url(array(
                            'controller'    => 'client-contact',
                            'action'        => 'edit',
                            'clientId'      => $contact->idClient,
                            'addressId'     => $contact->idAddress,
                            'contactId'     => $contact->idClientContact
                        )); ?>";
                    </script>
                </button>
			</td>
		</tr>
	<?php endforeach; ?>

<?php else: ?>
		<tr>
            <td colspan="6">This client has no contacts yet.</td>
        </tr>
<?php endif; ?>
</table>
