<div class="tableHead">
	<h2 class="tableHead-heading">Client Contacts</h2>
	<p class="tableHead-button">
		<a href="<?php echo $this->url(array(
			'controller'    => 'client-contact',
			'action'        => 'add',
			'clientId'      => $this->idClient
			), 'default', true);?>" class="button">New Contact</a>
	</p>
</div>

<table>
    <tr>
        <th>Name <span class="id">(id)</span></th>
        <th>Type</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Postcode</th>
        <th>&nbsp;</th>
    </tr>
<?php if ($this->contacts): ?>
	<?php foreach($this->contacts as $contact): ?>
		<tr>
			<td><?php echo $this->escape($contact->name); ?>&nbsp;
				<span class="id">(<?php echo $this->escape($contact->idClientContact); ?>)</span></td>
			<td><?php echo $this->escape($contact->type); ?></td>
			<td><?php echo $this->escape($contact->phone); ?></td>
			<td><?php echo $this->escape($contact->email); ?></td>
			<td><?php echo $this->escape($contact->postcode); ?></td>
			<td class="action">
				<a href="<?php echo $this->url(array(
					'controller'    => 'client-contact',
					'action'        => 'edit',
					'clientId'      => $contact->idClient,
					'addressId'     => $contact->idAddress,
					'contactId'     => $contact->idClientContact
				));?>" class="button">Edit</a>

				<a href="<?php echo $this->url(array(
					'controller'    => 'client-contact',
					'action'        => 'delete',
					'clientId'      => $contact->idClient,
					'addressId'     => $contact->idAddress,
					'contactId'     => $contact->idClientContact
				));?>" class="button">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>

<?php else: ?>
		<tr><td>This client has no contacts yet.</td>
		<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<?php endif; ?>
</table>
