<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'BBA System Error'" data-dojo-id="error">
    <div class="dijitDialogPaneContentArea">
        <div id="error-content">
            <h3>BBA Error</h3>
            <p>There was an error processing your request:</p>
            <p><?php echo $this->message; ?></p>
        </div>
        <button data-dojo-type="dijit.form.Button">
            Close
            <script type="dojo/method" data-dojo-event="onClick">
                return bba.closeDialog(error);
            </script>
        </button>
    </div>
</div>