<?php $this->dojo()->requireModule('bba/Auth', true); ?>
<div id="login" data-dojo-type="dijit.Dialog" data-dojo-id="login" data-dojo-props="title:'BBA Power Database'">
    <div class="dijitDialogPaneContentArea">
        <div id="loginWrap">
            <h3 style="text-align:center;">Please Login</h3>
            <?php echo $this->authLoginForm; ?>
        </div>
    </div>
    <script type="dojo/method" data-dojo-event="onHide">
        return bba.closeDialog(login);
    </script>
</div>