<button dojoType="dijit.form.Button"
        id="addMeterToContractButton"
        type="button"
        onClick="bba.Contract.addMeterToContract(contractMeterGrid, <?php echo $this->idContract; ?>);">
    Add to Contract
</button>

<button dojoType="dijit.form.Button"
        id="cancelButton"
        type="button"
        onClick="bba.Contract.closeDialog()">
    Cancel
</button>

<div dojoType="dijit.Tooltip" connectId="addMeterToContractButton">
    <p>
        Select meters to add by clicking on the row or the row selector on the left of the row.<br />
        To deselect a meter click on the row again or the row selector on the left of the row.<br />
        Edit "Expected Yearly Consumption" by double clicking on the cell.<br />
        When a row is selected it will be light blue in colour.<br />
        When you are ready to add meters click the "Add to Contract" button.
    </p>
</div>
<div>&nbsp;</div>

<span dojoType="dojo.data.ItemFileWriteStore"
      jsId="contractMeterStore"
      url="/meter-contract/store?meterContract_idContract=<?php echo $this->idContract; ?>"
      requestMethod="post"></span>

<div dojoType="dojox.grid.DataGrid"
       jsId="contractMeterGrid"
       store="contractMeterStore"
       structure="bba.gridLayouts.meterContract"
       query="{ meter_idMeter : '*' }"
       clientSort="true"
       selectionMode="multiple"
       rowSelector="10px"
       sortInfo="-5"
       style="width:100%;height:300px;"
       noDataMessage="<span class='dojoxGridNoData'>No meters available for this contract</span>">
</div>
