<span dojoType="dojo.data.ItemFileReadStore"
      jsid="contractMeterStore"
      url="/meter-contract/store?meterContract_idContract=<?php echo $this->idContract; ?>"
      requestMethod="post"></span>

<table dojoType="dojox.grid.DataGrid"
       jsId="contractMeterGrid"
       store="contractMeterStore"
       query="{ }"
       sortInfo="1"
       style="width:100%;height:300px;">
    <thead>
        <tr>
            <th field="meter_idMeter" width="50">Id</th>
            <th field="meter_numberMain" width="150">Number Main</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>
