<?php
	$this->title = 'Add New Meter';
	$this->headTitle($this->title);
/*
	$this->form->me_si_id->setDescription('&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
						<a href="'.$this->url(array(
											'controller'=>'site',
											'action'=>'addSite',
											'returnToControl'=>'meter',
											'returnToAction'=>'addMeter'
											)).'">Add New Site</a>');

	echo $this->form ;
 *
 */
    echo $this->meterAddForm;
?>