<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <table class="info_wrap">
                <caption>Meter Details <span class="id_number">(<?php echo $this->meter->meter_idMeter; ?>)</span></caption>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->meter->meter_type; ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->meter->meter_status; ?></td>
                </tr>
                <tr>
                    <th>Number Top:</th>
                    <td><?php echo $this->meter->meter_numberTop; ?></td>
                </tr>
                <tr>
                    <th>Number Main:</th>
                    <td><?php echo $this->meter->meter_numberMain; ?></td>
                </tr>
                <tr>
                    <th>Serial Number:</th>
                    <td><?php echo $this->meter->meter_numberSerial; ?></td>
                </tr>
                <tr>
                    <th>Supply Capacity:</th>
                    <td><?php echo $this->meter->meter_capacity; ?>&nbsp;kWH</td>
                </tr>

                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->meter->meter_desc; ?></td>
                </tr>

                <?php if ($this->isAllowed('User')): ?>
                <tr>
                    <td class="footer" colspan="2">
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Meter.editMeterButtonClick({
                                    meter_idMeter : <?php echo $this->meter->meter_idMeter; ?>
                                });
                            </script>
                        </button>
                    </td>
                </tr>
                <?php endif; ?>
            </table>

            <table class="info_wrap ident">
                <caption>Site Address <span class="id_number">(<?php echo $this->meter->clientAd_idAddress; ?>)</span></caption>
                <tr>
                    <td><?php
                        echo $this->formatAddress(array(
                            $this->escape($this->meter->client_name),
                            $this->escape($this->meter->clientAd_address1),
                            $this->escape($this->meter->clientAd_address2),
                            $this->escape($this->meter->clientAd_address3),
                            $this->escape($this->meter->clientAd_postcode)
                        ));
                    ?></td>
                </tr>
            </table>

            <table class="info_wrap ident contract_info">
                <caption>Contract Info: <span class="id_number">(<?php echo $this->escape($this->meter->contract_idContract); ?>)</span></caption>
                <?php if ($this->meter->contract_idContract): ?>
                <tr>
                    <th>Reference:</th>
                    <td><?php echo $this->escape($this->meter->contract_reference); ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->escape($this->meter->contract_desc); ?></td>
                </tr>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->escape($this->meter->contract_type); ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->escape($this->meter->contract_status); ?></td>
                </tr>
                <tr>
                    <th>Start Date:</th>
                    <td><?php echo $this->formatDate($this->meter->contract_dateStart); ?></td>
                </tr>
                <tr>
                    <th>End Date:</th>
                    <td><?php echo $this->formatDate($this->meter->contract_dateEnd); ?></td>
                </tr>
                <tr>
                    <th>Supplier:</th>
                    <td><?php echo $this->escape($this->meter->supplier_name); ?></td>
                </tr>
                <tr>
                    <th>Commission:</th>
                    <td><?php echo $this->escape($this->meter->tender_commission); ?> (pence / unit)</td>
                </tr>
                <tr>
                    <th>Peak kVA:</th>
                    <td><?php echo $this->escape($this->meter->	meterContract_kvaNominated); ?></td>
                </tr>
                <tr>
                    <th>EAC:</th>
                    <td><?php echo $this->escape($this->meter->	meterContract_eac); ?></td>
                </tr>
                <?php else: ?>
                <tr>
                    <td>No contract for this meter.</td>
                </tr>
                <?php endif; ?>
            </table>
            <div class="clear"></div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="meterEditTabs-BorderContainter">

        <div id="MeterTabs<?php echo $this->meter->meter_idMeter; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true', splitter: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Meter Usage'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'meter/data-store/type/usage', requestMethod: 'post'"
                    data-dojo-id="usageStore<?php echo $this->meter->meter_idMeter; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    id="usageGrid<?php echo $this->meter->meter_idMeter; ?>"
                    data-dojo-id="usageGrid<?php echo $this->meter->meter_idMeter; ?>"
                    data-dojo-props='
                        store: usageStore<?php echo $this->meter->meter_idMeter; ?>,
                        structure: bba.Meter.gridLayouts.meterUsage,
                        query: { usage_idMeter: <?php echo $this->meter->meter_idMeter; ?> },
                        sortInfo: "-2",
                        noDataMessage : bba.gridMessage'>
                    <?php if ($this->isAllowed('MeterUsage')): ?>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Meter.usageGridRowClick(this);
                    </script>
                    <?php endif; ?>
                </table>
            </div>

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Meter Contracts'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'meter/data-store/type/contract', requestMethod: 'post'"
                    data-dojo-id="contractStore"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    data-dojo-id="contractGrid"
                    data-dojo-props='
                        store: contractStore,
                        structure: bba.Meter.gridLayouts.contract,
                        query: { meter_idMeter: <?php echo $this->meter->meter_idMeter; ?> },
                        sortInfo: "3",
                        noDataMessage : bba.gridMessage'>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Contract.contractGridRowClick(this);
                    </script>
                </table>
            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('MeterUsage')): ?>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button"
                            data-dojo-props="onClick: bba.Meter.newUsageButtonClick"
                            type="button"
                            value="<?php echo $this->meter->meter_idMeter; ?>"
                            id="new-usage-button-<?php echo $this->meter->meter_idMeter; ?>">
                    New Usage
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Meter.newUsageButtonClick({
                            usage_idMeter : <?php echo $this->meter->meter_idMeter; ?>
                        });
                    </script>
                </button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>

