<?php
	$this->title = 'Edit Meter';
	$this->headTitle($this->title);
?>

<div style="float:left;margin:5px;">
    <p><?php echo $this->meter->client_name; ?> </p>
    <p><?php echo $this->formatSiteAddress(array(
        $this->escape($this->meter->clientAd_address1),
        $this->escape($this->meter->clientAd_address2),
        $this->escape($this->meter->clientAd_address3),
        $this->escape($this->meter->clientAd_postcode)
    )); ?></p>
</div>

<div style="float:left;margin:5px;margin-left:30px;">
    <?php echo $this->meterSaveForm; ?>
</div>

<div class="clear"></div>

<script>
    var usageStore = <?php echo $this->usageStore; ?>;

    dojo.addOnLoad(function(){
        dojo.connect(usageGrid, "onRowDblClick", function(val){
            selectedIndex = usageGrid.focus.rowIndex;
            selectedItem = usageGrid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = usageGrid.store.getValue(selectedItem, "usage_idUsage");

            location.href = '/usage/edit/usageId/' + selectedId;
        });
    });

</script>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Usage',
    'label'     => 'Add Usage',
    'location'  => $this->url(array(
        'controller'    => 'usage',
        'action'        => 'add',
        'meterId'    => $this->meter->id
    ),'default', true)
)); ?>

<div dojotype="dojo.data.ItemFileReadStore" jsid="usageTableStore" data="usageStore"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="usageGrid"
       store="usageTableStore"
       query="{ usage_idUsage: '*' }"
       style="width: 100%;"
       autowidth="false"
       autoHeight="10"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="usage_idUsage" width="100">Id</th>
            <th field="usage_dateBill" width="100">Bill Date</th>
            <th field="usage_dateReading" width="100">Reading Date</th>
            <th field="usage_type" width="100">Type</th>
            <th field="usage_usageDay" width="auto">Day</th>
            <th field="usage_usageNight" width="auto">Night</th>
            <th field="usage_usageOther" width="auto">Other</th>
        </tr>
    </thead>
</table>
