<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <table class="info_wrap">
                <caption>Meter Details</caption>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->meter->meter_type; ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->meter->meter_status; ?></td>
                </tr>
                <tr>
                    <th>Serial Number:</th>
                    <td><?php echo $this->meter->meter_numberSerial; ?></td>
                </tr>
                <tr>
                    <th>Number Top:</th>
                    <td><?php echo $this->meter->meter_numberTop; ?></td>
                </tr>
                <tr>
                    <th>Number Main:</th>
                    <td><?php echo $this->meter->meter_numberMain; ?></td>
                </tr>

                <?php if ($this->isAllowed('User')): ?>
                <tr>
                    <td class="footer" colspan="2">
                        <div dojoType="dijit.form.Form"
                             id="edit-meter-<?php echo $this->meter->meter_idMeter; ?>">
                            <button dojoType="dijit.form.Button"
                                    type="submit"
                                    name="edit-meter-button-<?php echo $this->meter->meter_idMeter; ?>"
                                    value="submit">Edit Details</button>
                        </div>
                    </td>
                </tr>
                <?php endif; ?>
            </table>

            <table class="info_wrap ident">
                <caption>Site Address</caption>
                <tr>
                    <td><?php
                        echo $this->formatAddress(array(
                            $this->escape($this->meter->client_name),
                            $this->escape($this->meter->clientAd_address1),
                            $this->escape($this->meter->clientAd_address2),
                            $this->escape($this->meter->clientAd_address3),
                            $this->escape($this->meter->clientAd_postcode)
                        ));
                    ?></td>
                </tr>
            </table>

            <?php if ($this->meter->contract_idContract): ?>
            <table class="info_wrap ident contract_info">
                <caption>Contract Info: <span class="id_number">(<?php echo $this->escape($this->meter->contract_idContract); ?>)</span></caption>
                <tr>
                    <th>Reference:</th>
                    <td><?php echo $this->escape($this->meter->contract_reference); ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->escape($this->meter->contract_desc); ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->escape($this->meter->contract_status); ?></td>
                </tr>
                <tr>
                    <th>Start Date:</th>
                    <td><?php echo $this->formatDate($this->meter->contract_dateStart); ?></td>
                </tr>
                <tr>
                    <th>End Date:</th>
                    <td><?php echo $this->formatDate($this->meter->contract_dateEnd); ?></td>
                </tr>
                <tr>
                    <th>Supplier:</th>
                    <td><?php echo $this->escape($this->meter->supplier_name); ?></td>
                </tr>
                <tr>
                    <th>Commission:</th>
                    <td><?php echo $this->escape($this->meter->tender_commission); ?></td>
                </tr>
            </table>
            <?php endif; ?>
            <div class="clear"></div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="meterEditTabs-BorderContainter">

        <div id="MeterTabs<?php echo $this->meter->meter_idMeter; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true', splitter: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Meter Usage'">

                <span dojoType="dojox.data.QueryReadStore"
                     jsid="usageStore<?php echo $this->meter->meter_idMeter; ?>"
                     url="/meter/data-store/type/usage"
                     requestMethod="post"></span>

                <table dojoType="bba.DataGrid"
                       jsId="usageGrid<?php echo $this->meter->meter_idMeter; ?>"
                       store="usageStore<?php echo $this->meter->meter_idMeter; ?>"
                       structure="bba.Meter.gridLayouts.meterUsage"
                       query="{ usage_idMeter: <?php echo $this->meter->meter_idMeter; ?> }"
                       queryParent="usage_idMeter"
                       sortInfo="-3"
                       dialog="true"
                       dialogName="Consumption for period"
                       newButtonId="<?php echo $this->meter->meter_idMeter; ?>"
                       controller="meter">
                </table>
            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <p class="tableHead-button">
                <button dojoType="dijit.form.Button"
                        id="new-usage-button-<?php echo $this->meter->meter_idMeter; ?>"
                        type="button">New Usage</button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>

