<?php $site = $this->meter->getSite(); ?>
<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top', splitter: 'true'">
        <div class="tabHeading">
            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Meter Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->meter->meter_idMeter; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('User')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Meter.editMeterButtonClick({
                                    meter_idMeter : <?php echo $this->meter->meter_idMeter; ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Client:</th>
                    <td><?php echo $site->getClient('client_name'); ?></td>
                </tr>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->meter->getMeterType(); ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->meter->getMeterStatus(); ?></td>
                </tr>
                <tr>
                    <th>Number Top:</th>
                    <td><?php echo $this->meter->meter_numberTop; ?></td>
                </tr>
                <tr>
                    <th>Number Main:</th>
                    <td><?php echo $this->meter->meter_numberMain; ?></td>
                </tr>
                <tr>
                    <th>Serial Number:</th>
                    <td><?php echo $this->meter->meter_numberSerial; ?></td>
                </tr>
                <tr>
                    <th>Supply Capacity:</th>
                    <td><?php echo $this->meter->meter_capacity; ?>&nbsp;kVA</td>
                </tr>

                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->meter->getShortDesc(); ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>Site <span class="id_number">(<?php echo $site->site_idSite; ?>)</span></caption>
                <tr>
                    <td><?php
                        echo $this->formatAddress(array(
                            $site->getSiteAddress('clientAd_addressName'),
                            $site->getSiteAddress('clientAd_address1'),
                            $site->getSiteAddress('clientAd_address2'),
                            $site->getSiteAddress('clientAd_address3'),
                            $site->getSiteAddress('clientAd_postcode')
                        ));
                    ?></td>
                </tr>
            </table>

            <?php $contract = $this->meter->getCurrentContract(); ?>
            <table class="info_wrap ident contract_info">
                <caption>Current Contract: <span class="id_number">(<?php echo $this->escape($contract->contract_idContract); ?>)</span></caption>
                <?php if ($contract->contract_idContract): ?>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->escape($contract->getContractType()); ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->escape($contract->getContractStatus()); ?></td>
                </tr>
                <tr>
                    <th>Start Date:</th>
                    <td><?php echo $this->formatDate($contract->contract_dateStart); ?></td>
                </tr>
                <tr>
                    <th>End Date:</th>
                    <td><?php echo $this->formatDate($contract->contract_dateEnd); ?></td>
                </tr>
                <tr>
                    <th>Reference:</th>
                    <td><?php echo $this->escape($contract->contract_reference); ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->escape($contract->getShortDesc()); ?></td>
                </tr>
                <?php if ($contract->contract_idTenderSelected): ?>
                <tr>
                    <th>Supplier:</th>
                    <td><?php echo $this->escape($contract->getTenderSelected()->getSupplier('supplier_name')); ?></td>
                </tr>
                <tr>
                    <th>Commission Rate:</th>
                    <td><?php echo $this->escape($contract->getTenderSelected('tender_commission')); ?> (pence / unit)</td>
                </tr>
                <tr>
                    <th>Commission Fee:</th>
                    <td><?php echo $this->escape($contract->getTenderSelected('tender_fee')); ?> (&pound; / Year)</td>
                </tr>
                <?php else: ?>
                <tr>
                    <td colspan="2">- No Tender Has Been Selected -</td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Peak kVA:</th>
                    <td><?php echo $this->escape($contract->meterContract_kvaNominated); ?></td>
                </tr>
                <tr>
                    <th>EAC:</th>
                    <td><?php echo $this->escape($contract->meterContract_eac); ?></td>
                </tr>
                <?php else: ?>
                <tr>
                    <td>No contract for this meter.</td>
                </tr>
                <?php endif; ?>
            </table>
            <div class="clear"></div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'center'"
         class="meterEditTabs-BorderContainter">

        <div id="MeterTabs<?php echo $this->meter->meter_idMeter; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true', splitter: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Consumption'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'meter/data-store/type/usage', requestMethod: 'post'"
                    data-dojo-id="usageStore<?php echo $this->meter->meter_idMeter; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    id="usageGrid<?php echo $this->meter->meter_idMeter; ?>"
                    data-dojo-id="usageGrid<?php echo $this->meter->meter_idMeter; ?>"
                    data-dojo-props='
                        store: usageStore<?php echo $this->meter->meter_idMeter; ?>,
                        structure: bba.Meter.gridLayouts.meterUsage,
                        query: { usage_idMeter: <?php echo $this->meter->meter_idMeter; ?> },
                        sortInfo: "-2",
                        selectable: true,
                        noDataMessage : bba.gridMessage'>
                    <?php if ($this->isAllowed('MeterUsage')): ?>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Meter.usageGridRowClick(this);
                    </script>
                    <?php endif; ?>
                </table>
            </div>

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Contracts'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'meter/data-store/type/contract', requestMethod: 'post'"
                    data-dojo-id="meterContractStore"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    data-dojo-id="contractGrid"
                    data-dojo-props='
                        store: meterContractStore,
                        structure: bba.Meter.gridLayouts.contract,
                        query: { meter_idMeter: <?php echo $this->meter->meter_idMeter; ?> },
                        sortInfo: "-4",
                        noDataMessage : bba.gridMessage'>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Contract.contractGridRowClick(this);
                    </script>
                </table>
            </div>
            <?php if ($this->isAllowed('Admin')): ?>
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Invoice Lines'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'invoice/data-store/type/invoice-lines', requestMethod: 'post'"
                      data-dojo-id="meterInvoiceLinesStore<?php echo $this->meter->meter_idMeter; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="meterInvoiceLinesGrid<?php echo $this->meter->meter_idMeter; ?>"
                       id="meterInvoiceLinesGrid<?php echo $this->meter->meter_idMeter; ?>"
                       data-dojo-props='
                           store: meterInvoiceLinesStore<?php echo $this->meter->meter_idMeter; ?>,
                           structure: bba.Meter.gridLayouts.invoiceLines,
                           query: { invoiceLine_idMeter: <?php echo $this->meter->meter_idMeter; ?> },
                           sortInfo: "-4",
                           noDataMessage : bba.gridMessage'>
                    <script type="dojo/method" data-dojo-event="onCellClick" args="e">
                        var colField = e.cell.field
                        bba.Invoice.invoiceLineGridRowClick(this, e, colField);
                    </script>
                </table>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('MeterUsage')): ?>
            <p class="tableHead-button">
            	<button data-dojo-type="dijit.form.Button">
                    New Contract
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Contract.newContractButtonClick({
                            contract_idClient : <?php echo $site->site_idClient; ?>,
							meter_idMeter : <?php echo $this->meter->meter_idMeter; ?>,
							meter_type : '<?php echo $this->meter->meter_type; ?>'
                        });
                    </script>
                </button>
                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: bba.Meter.newUsageButtonClick"
                        type="button"
                        value="<?php echo $this->meter->meter_idMeter; ?>"
                        id="new-usage-button-<?php echo $this->meter->meter_idMeter; ?>">
                    New Usage
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Meter.newUsageButtonClick({
                            usage_idMeter : <?php echo $this->meter->meter_idMeter; ?>
                        });
                    </script>
                </button>

            </p>
 
                <form action="meter/print-meter" method="post" target="_blank">

                    <input type="hidden" name="meter_idMeter" value="<?php echo $this->meter->meter_idMeter; ?>" />
                    <button data-dojo-type="dijit.form.Button" type="submit">
                        Print Meter Details
                    </button>
                </form>

           <?php endif; ?>
        </div>
    </div>
</div>

