<?php
	$this->title = "BBA Meters";
	$this->headTitle($this->title);

    echo $this->meterSearchForm;
?>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Meters',
    'label'     => 'New Meter'
)); ?>

<script>
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "meter_idMeter");

            var url = '/meter/edit/meterId/' + selectedId;

            <?php //foreach($this->search as $key => $value): ?>
                    <?php //if($value): ?>
                        //url = url + '/<?php //echo $key; ?>' + '/<?php //echo $value; ?>';
                    <?php //endif; ?>
            <?php //endforeach; ?>

            location.href = url;
        });
    });

</script>

<div dojotype="dojox.data.QueryReadStore"
     jsid="tableStore"
     url="/meter/meter-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="grid"
       store="tableStore"
       query="<?php echo $this->search; ?>"
       style="width: 100%;height:500px;"
       autoWidth="false"
       autoHeight="false"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="meter_idMeter" width="50">Id</th>
            <th field="client_name" width="200">Client</th>
            <th field="clientAd_addressName" width="200">Address Name</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
            <th field="meter_type" width="100">Meter Type</th>
            <th field="meter_numberMain" width="120">Meter #</th>
            <th field="contract_status" width="80">Contract</br>Status</th>
            <th field="contract_dateEnd" width="100">End Date</th>
			<th field=" " width="auto"> </th>
        </tr>
    </thead>
</table>

<?php
/*
if ($this->meters instanceof Zend_Paginator) {
    echo $this->paginationControl(
            $this->meters,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}*/
?>