<?php
	$this->title = "BBA Meters";
	$this->headTitle($this->title);

    echo $this->meterSearchForm;
?>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Meters',
    'label'     => 'New Meter'
)); ?>

<script>
    var meterStore = <?php echo $this->store; ?>;
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "meter_idMeter");

            var url = '/meter/edit/meterId/' + selectedId;

            <?php foreach($this->search as $key => $value): ?>
                    <?php if($value): ?>
                        url = url + '/<?php echo $key; ?>' + '/<?php echo $value; ?>';
                    <?php endif; ?>
            <?php endforeach; ?>

            location.href = url;
        });
    });

</script>

<div dojotype="dojo.data.ItemFileReadStore" jsid="tableStore" data="meterStore"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="grid"
       store="tableStore"
       query="{ meter_idMeter: '*' }"
       style="width: 100%;height:500px;"
       autoWidth="false"
       autoHeight="false"
       rowSelector="0px"
       rowsPerPage="25"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="meter_idMeter" width="75">Id</th>
            <th field="client_name" width="200">Client</th>
            <th field="clientAd_addressName" width="200">Address Name</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
            <th field="meter_type" width="100">Meter Type</th>
            <th field="meter_numberMain" width="150">MPAN13</th>
            <th field="contract_status" width="150">Contract Status</th>
            <th field="contract_dateEnd" width="auto">End Date</th>
        </tr>
    </thead>
</table>

<?php
/*
if ($this->meters instanceof Zend_Paginator) {
    echo $this->paginationControl(
            $this->meters,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}*/
?>