<?php $this->dojo()->requireModule('bba/Meter', true); ?>
<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">

        <div class="tabHeading">
            <?php
                $this->title = "BBA Meters";
                $this->headTitle($this->title);

                echo $this->meterSearchForm;
            ?>

            <div class="tableHead">
                <h2 class="tableHead-heading">Meters:</h2>
                <?php if ($this->isAllowed('User')): ?>
                <p class="tableHead-button">
                    To add a Meter: display the required Site.
                </p>
                <?php endif; ?>

            </div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <span data-dojo-type="dojox.data.QueryReadStore"
              data-dojo-props="url: '/meter/data-store/type/meter', requestMethod: 'post'"
              data-dojo-id="meterStore"></span>

        <table data-dojo-type="dojox.grid.DataGrid"
            data-dojo-id="meterGrid"
            id="meterGrid"
            data-dojo-props='
                store: meterStore,
                structure: bba.Meter.gridLayouts.meter,
                query: <?php echo $this->search; ?>,
                sortInfo: "2",
                noDataMessage : bba.gridMessage,
                onRowClick: bba.Meter.meterGridRowClick'>
        </table>
    </div>
</div>