<?php
$form = $this->meterSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="meterForm"
     data-dojo-id="meterForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Meter',
        execute: bba.Meter.processMeterForm">
    <div class="dijitDialogPaneContentArea">

        <div class="form_wrap meter-add">
            <div class="zend_form">

                <?php  if ($this->request()->getParam('type') == 'add'): ?>
                    <?php echo $form->meter_type; ?>
                <?php else: ?>
                    <input dojoType="dijit.form.TextBox"
                           type="hidden"
                           name="meter_type"
                           id="meter_type"
                           required="true"
                           value="<?php echo $form->meter_type->getValue(); ?>" />
                    Meter Type: <?php echo $form->meter_type->getValue(); ?>
                <?php endif; ?>

                <?php echo $form->meter_status; ?>

                <?php echo $form->meter_numberSerial; ?>

                <?php echo $form->meter_numberTop; ?>

                <?php echo $form->meter_numberMain; ?>

                <?php echo $form->meter_capacity; ?>

                <?php echo $form->meter_desc; ?>

                <input dojoType="dijit.form.TextBox"
                       type="hidden"
                       name="meter_idMeter"
                       id="meter_idMeter"
                       required="true"
                       value="<?php echo $form->meter_idMeter->getValue(); ?>" />

                <input dojoType="dijit.form.TextBox"
                       type="hidden"
                       name="meter_idSite"
                       id="meter_idSite"
                       required="true"
                       value="<?php echo $form->meter_idSite->getValue(); ?>" />

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return dijit.byId('meterForm').validate();}"
                        type="submit"
                        id="meterFormSubmitButton">Save</button>

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return bba.closeDialog(dijit.byId('meterForm'));}"
                        id="meterFormCancelButton">Cancel</button>
            </div>
        </div>
    </div>
</div>