<div data-dojo-type="dijit.Dialog"
     id="meterForm"
     data-dojo-id="meterForm"
     data-dojo-props="
        title:'<?php echo $this->type; ?> Meter',
        execute: bba.Meter.processMeterForm">
    <div class="dijitDialogPaneContentArea">

        <div class="form_wrap meter-add">
            <div class="zend_form">

                <?php echo $this->meterForm; ?>
                
                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<div data-dojo-id="meterFormStandby"
     data-dojo-type="dojox.widget.Standby"
     data-dojo-props="target:'meterForm', color: '#efefef', image: 'images/loader_lg.gif'"></div>