
<table id="meter_details">
    <caption>Meter Details <span class="id_number">(<?php echo $this->meter->meter_idMeter; ?>)</span></caption>
    <tr>
        <th>Type:</th>
        <td><?php echo $this->meter->meter_type; ?></td>
    </tr>
    <tr>
        <th>Status:</th>
        <td><?php echo $this->meter->meter_status; ?></td>
    </tr>
    <tr>
        <th>Number Top:</th>
        <td><?php echo $this->meter->meter_numberTop; ?></td>
    </tr>
    <tr>
        <th>Number Main:</th>
        <td><?php echo $this->meter->meter_numberMain; ?></td>
    </tr>
    <tr>
        <th>Serial Number:</th>
        <td><?php echo $this->meter->meter_numberSerial; ?></td>
    </tr>
    <tr>
        <th>Supply Capacity:</th>
        <td><?php echo $this->meter->meter_capacity; ?>&nbsp;kVA</td>
    </tr>

    <tr>
        <th>Description:</th>
        <td class="description"><?php echo $this->meter->meter_desc; ?></td>
    </tr>
</table>

<table id="client_address">
    <caption>Site Address <span class="id_number">(<?php echo $this->meter->clientAd_idAddress; ?>)</span></caption>
    <tr>
        <th>Address Name:</th>
        <td><?php echo $this->escape("(".$this->meter->clientAd_addressName.")"); ?></td>
    </tr>
    <tr>
        <th>Client Name:</th>
        <td><?php echo $this->escape($this->meter->client_name); ?></td>
    </tr>
    <tr>
        <th>Address 1:</th>
        <td><?php echo $this->escape($this->meter->clientAd_address1); ?></td>
    </tr>
    <tr>
        <th>Address 2</th>
        <td><?php echo $this->escape($this->meter->clientAd_address2); ?></td>
    </tr>
    <tr>
        <th>Town/City:</th>
        <td><?php echo $this->escape($this->meter->clientAd_address3); ?></td>
    </tr>
    <tr>
        <th>Postcode:</th>
        <td><?php echo $this->escape($this->meter->clientAd_postcode); ?></td>
    </tr>
    <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
    </tr>
</table>

<table id="meter_contract">
    <caption>Contract Info: <span class="id_number">(<?php echo $this->escape($this->meter->contract_idContract); ?>)</span></caption>
    <?php if ($this->meter->contract_idContract): ?>
    <tr>
        <th>Reference:</th>
        <td><?php echo $this->escape($this->meter->contract_reference); ?></td>
    </tr>
    <tr>
        <th>Description:</th>
        <td class="description"><?php echo $this->escape($this->meter->contract_desc); ?></td>
    </tr>
    <tr>
        <th>Type:</th>
        <td><?php echo $this->escape($this->meter->contract_type); ?></td>
    </tr>
    <tr>
        <th>Status:</th>
        <td><?php echo $this->escape($this->meter->contract_status); ?></td>
    </tr>
    <tr>
        <th>Start Date:</th>
        <td><?php echo $this->formatDate($this->meter->contract_dateStart); ?></td>
    </tr>
    <tr>
        <th>End Date:</th>
        <td><?php echo $this->formatDate($this->meter->contract_dateEnd); ?></td>
    </tr>
    <tr>
        <th>Supplier:</th>
        <td><?php echo $this->escape($this->meter->supplier_name); ?></td>
    </tr>
    <tr>
        <th>Commission:</th>
        <td><?php echo $this->escape($this->meter->tender_commission); ?> (pence / unit)</td>
    </tr>
    <tr>
        <th>Peak kVA:</th>
        <td><?php echo $this->escape($this->meter->	meterContract_kvaNominated); ?></td>
    </tr>
    <tr>
        <th>EAC:</th>
        <td><?php echo $this->escape($this->meter->	meterContract_eac); ?></td>
    </tr>
    <?php else: ?>
    <tr>
        <td>No contract for this meter.</td>
    </tr>
    <?php endif; ?>
</table>

<script>window.print();</script>

