
<table id="meter_details">
    <caption>Meter Details <span class="id_number">(<?php echo $this->meter->meter_idMeter; ?>)</span></caption>
    <tr>
        <th>Type:</th>
        <td><?php echo $this->meter->meter_type; ?></td>
    </tr>
    <tr>
        <th>Status:</th>
        <td><?php echo $this->meter->meter_status; ?></td>
    </tr>
    <tr>
        <th>Number Top:</th>
        <td><?php echo $this->meter->meter_numberTop; ?></td>
    </tr>
    <tr>
        <th>Number Main:</th>
        <td><?php echo $this->meter->meter_numberMain; ?></td>
    </tr>
    <tr>
        <th>Serial Number:</th>
        <td><?php echo $this->meter->meter_numberSerial; ?></td>
    </tr>
    <tr>
        <th>Supply Capacity:</th>
        <td><?php echo $this->meter->meter_capacity; ?>&nbsp;kVA</td>
    </tr>

    <tr>
        <th>Description:</th>
        <td class="description"><?php echo $this->meter->meter_desc; ?></td>
    </tr>
</table>

<?php $site = $this->meter->getSite(); ?>
<table id="client_address">
    <caption>Site Address <span class="id_number">(<?php echo $site->getSiteAddress('clientAd_idAddress'); ?>)</span></caption>
    <tr>
        <th>Address Name:</th>
        <td><?php echo $this->escape("(".$site->getSiteAddress('clientAd_addressName').")"); ?></td>
    </tr>
    <tr>
        <th>Client Name:</th>
        <td><?php echo $this->escape($site->getClient('client_name')); ?></td>
    </tr>
    <tr>
        <th>Address 1:</th>
        <td><?php echo $this->escape($site->getSiteAddress('clientAd_address1')); ?></td>
    </tr>
    <tr>
        <th>Address 2</th>
        <td><?php echo $this->escape($site->getSiteAddress('clientAd_address2')); ?></td>
    </tr>
    <tr>
        <th>Town/City:</th>
        <td><?php echo $this->escape($site->getSiteAddress('clientAd_address3')); ?></td>
    </tr>
    <tr>
        <th>Postcode:</th>
        <td><?php echo $this->escape($site->getSiteAddress('clientAd_postcode')); ?></td>
    </tr>
    <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
    </tr>
</table>

<?php $contract = $this->meter->getCurrentContract(); ?>
<table id="meter_contract">
    <caption>Contract Info: <span class="id_number">(<?php echo $this->escape($contract->contract_idContract); ?>)</span></caption>
    <?php if ($contract->contract_idContract): ?>
    <tr>
        <th>Reference:</th>
        <td><?php echo $this->escape($contract->contract_reference); ?></td>
    </tr>
    <tr>
        <th>Description:</th>
        <td class="description"><?php echo $this->escape($contract->contract_desc); ?></td>
    </tr>
    <tr>
        <th>Type:</th>
        <td><?php echo $this->escape($contract->contract_type); ?></td>
    </tr>
    <tr>
        <th>Status:</th>
        <td><?php echo $this->escape($contract->contract_status); ?></td>
    </tr>
    <tr>
        <th>Start Date:</th>
        <td><?php echo $this->formatDate($contract->contract_dateStart); ?></td>
    </tr>
    <tr>
        <th>End Date:</th>
        <td><?php echo $this->formatDate($contract->contract_dateEnd); ?></td>
    </tr>
    <tr>
        <th>Supplier:</th>
        <td><?php if ($contract->getTenderSelected()): ?>
                <?php echo $this->escape($contract->getTenderSelected()->getSupplier('supplier_name')); ?>
            <?php else: ?>
                No Supplier Has Been Selected
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th>Commission:</th>
        <td><?php if ($contract->getTenderSelected()): ?>
                <?php echo $this->escape($contract->getTenderSelected('tender_commission')); ?> (pence / unit)
            <?php else: ?>
                No Tender Has Been Selected
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th>Peak kVA:</th>
        <td><?php echo $this->escape($contract->meterContract_kvaNominated); ?></td>
    </tr>
    <tr>
        <th>EAC:</th>
        <td><?php echo $this->escape($contract->meterContract_eac); ?></td>
    </tr>
    <?php else: ?>
    <tr>
        <td>No contract for this meter.</td>
    </tr>
    <?php endif; ?>
</table>

<script>window.print();</script>

