<?php
$form = $this->meterUsageSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="usageForm"
     data-dojo-id="usageForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Meter Consumption For Period',
        execute: bba.Meter.processUsageForm">
    <div class="dijitDialogPaneContentArea">

        <div class="dialog_title">
            
        </div>

        <div class="form_wrap">
            <div class="zend_form">

                <?php echo $form->usage_dateReading; ?>

                <?php echo $form->usage_type; ?>

                <?php echo $form->usage_usageDay; ?>

                <?php echo $form->usage_usageNight; ?>

                <?php echo $form->usage_usageOther; ?>

                <?php if ($form->getErrorMessages()): ?>
                    <?php foreach ($form->getErrorMessages() as $error): ?>
                        <p class="errors"><?php echo $error; ?></p>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php echo $form->usage_dateBill; ?>
                
                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>

                <input dojoType="dijit.form.TextBox"
                    type="hidden"
                    name="usage_idUsage"
                    id="usage_idUsage"
                    required="true"
                    value="<?php echo $form->usage_idUsage->getValue(); ?>" />

                <input dojoType="dijit.form.TextBox"
                    type="hidden"
                    name="usage_idMeter"
                    id="usage_idMeter"
                    required="true"
                    value="<?php echo $form->usage_idMeter->getValue(); ?>" />

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return dijit.byId('usageForm').validate();}"
                        type="submit"
                        id="meterFormSubmitButton">Save</button>

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return bba.closeDialog(dijit.byId('usageForm'));}"
                        id="meterFormCancelButton">Cancel</button>
            </div>
        </div>

    </div>
</div>