<span dojoType="dojox.data.QueryReadStore"
     jsid="clientContactStore<?php echo $this->idClient; ?>"
     url="/client-contact/client-contact-store"
     requestMethod="post"></span>

<table dojoType="dojox.grid.DataGrid"
       jsId="contactGrid<?php echo $this->idClient; ?>"
       store="clientContactStore<?php echo $this->idClient; ?>"
       query="{ clientCo_idClient: <?php echo $this->idClient; ?> }"
       queryParent="clientCo_idClient"
       sortInfo="2"
       dialog="true"
       dialogName="Edit Client Contact">
    <thead>
        <tr>
            <th field="clientCo_idClientContact" width="75">Id</th>
            <th field="clientCo_type" width="250">Type</th>
            <th field="clientCo_phone" width="300">Phone</th>
            <th field="clientCo_email" width="200">Email</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>
