<?php
	$this->title = "BBA Client Contact Update";
	$this->headTitle($this->title);
?>
<h3>Client Name: <?php echo $this->clientHelper($this->client, 'name'); ?></h3>
<?php
    echo $this->clientContactSaveForm;

    echo $this->partial('_client-addresses.phtml', array(
        'idClient'      => $this->client,
        'addresses'     => $this->clientAddresses($this->client)
    ));

    echo $this->partial('_client-contacts.phtml', array(
        'idClient'  => $this->client,
        'currentEdit' => $this->idClientContact,
        'contacts'  => $this->clientContacts($this->client)
    ));
?>