<?php
    $this->title = "BBA Users List";
	$this->headTitle($this->title);
    /* @var $user Power_Model_User */
?>

<script>
    var userStore = <?php echo $this->userStore; ?>;

    dojo.addOnLoad(function(){
        dojo.connect(userGrid, "onRowDblClick", function(val){
            selectedIndex = userGrid.focus.rowIndex;
            selectedItem = userGrid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = userGrid.store.getValue(selectedItem, "user_idUser");

            location.href = '/users/edit/userId/' + selectedId;
        });
    });

</script>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Users',
    'label'     => 'Add User',
    'location'  => $this->url(array(
        'controller'    => 'users',
        'action'        => 'add'
    ),'default', true)
)); ?>

<div dojotype="dojo.data.ItemFileReadStore" jsid="userTableStore" data="userStore"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="userGrid"
       store="userTableStore"
       query="{ user_idUser: '*' }"
       style="width: 100%;"
       autowidth="false"
       autoHeight="10"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="user_idUser" width="75">Id</th>
            <th field="user_name" width="200">Username</th>
            <th field="user_fullName" width="200">Name</th>
            <th field="user_role" width="auto">Role</th>
        </tr>
    </thead>
</table>