<span dojoType="dojox.data.QueryReadStore"
     jsid="clientAddressStore<?php echo $this->idClient; ?>"
     url="/client-address/client-address-store"
     requestMethod="post"></span>

<table dojoType="dojox.grid.DataGrid"
       jsId="addressGrid<?php echo $this->idClient; ?>"
       store="clientAddressStore<?php echo $this->idClient; ?>"
       query="{ clientAd_idClient: <?php echo $this->idClient; ?> }"
       queryParent="clientAd_idClient"
       sortInfo="2"
       tabs="true"
       tabTitleColumn="clientAd_addressName">
    <thead>
        <tr>
            <th field="clientAd_idAddress" width="50">Id</th>
            <th field="clientAd_addressName" width="250">Address Name</th>
            <th field="clientAd_address1" width="300">Address 1</th>
            <th field="clientAd_address2" width="200">Address 2</th>
            <th field="clientAd_address3" width="100">Address 3</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>
