<?php
	$this->title = "BBA Client Address Update";
	$this->headTitle($this->title);

?>
<h3>Client Name: <?php echo $this->clientHelper($this->clientAd->idClient, 'name'); ?></h3>

<div class="form_wrap">
    <?php echo $this->clientAddressSaveForm; ?>
</div>

<?php echo $this->partial('_client-addresses.phtml', array(
    'clientId'      => $this->clientAd->idClient,
    'currentEdit'   => $this->clientAd->idAddress,
    'addressStore'  => $this->addressStore
)); ?>
<?php /* Commented out for V1 - clientContacts needs more thought about the associated address
echo $this->partial('_client-contacts.phtml', array(
    'idClient'  => $this->clientAd->idClient,
    'contacts'  => $this->clientContacts($this->clientAd->idClient)
)); */?>