<?php
	$this->title = "BBA Client Address Update";
	$this->headTitle($this->title);

?>
<h3>Client Name: <?php echo $this->clientHelper($this->client, 'name'); ?></h3>
<?php

    echo $this->clientAddressSaveForm;

    echo $this->partial('_client-addresses.phtml', array(
        'idClient'      => $this->client,
        'currentEdit' => $this->idAddress,
        'addresses'     => $this->clientAddresses($this->client)
    ));

    echo $this->partial('_client-contacts.phtml', array(
        'idClient'  => $this->client,
        'contacts'  => $this->clientContacts($this->client)
    ));
?>