<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <div class="tabHeading">
            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Supplier Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->supplier->supplier_idSupplier; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('User')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Supplier.editSupplierButtonClick({
                                    supplier_idSupplier : <?php echo $this->supplier->supplier_idSupplier; ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Supplier Name:</th>
                    <td><?php echo $this->supplier->supplier_name; ?></td>
                </tr>
                <tr>
                    <th>Address:</th>
                    <td><?php echo $this->supplier->getFullAddress(); ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>Main Liaison</caption>
                <tr>
                    <td><?php echo $this->supplier->getFullPersonnelAddress(); ?></td>
                </tr>
            </table>
            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="supplierEditTabs-BorderContainter">

        <div id="SupplierTabs<?php echo $this->supplier->supplier_idSupplier; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Contracts'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'supplier/data-store/type/contract', requestMethod: 'post'"
                    data-dojo-id="contractStore<?php echo $this->supplier->supplier_idSupplier; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    data-dojo-id="contractGrid<?php echo $this->supplier->supplier_idSupplier; ?>"
                    id="contractGrid<?php echo $this->supplier->supplier_idSupplier; ?>"
                    data-dojo-props="
                        store: contractStore<?php echo $this->supplier->supplier_idSupplier; ?>,
                        structure: bba.Supplier.gridLayouts.supplierContract,
                        query: { tender_idSupplier: <?php echo $this->supplier->supplier_idSupplier; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Contract.contractGridRowClick(this);
                    </script>
                </table>
            </div>

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Supplier Pesonnel'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'supplier/data-store/type/personnel', requestMethod: 'post'"
                    data-dojo-id="supplierPersStore<?php echo $this->supplier->supplier_idSupplier; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    data-dojo-id="supplierPersGrid<?php echo $this->supplier->supplier_idSupplier; ?>"
                    id="supplierPersGrid<?php echo $this->supplier->supplier_idSupplier; ?>"
                    data-dojo-props="
                        store: supplierPersStore<?php echo $this->supplier->supplier_idSupplier; ?>,
                        structure: bba.Supplier.gridLayouts.supplierPersonnel,
                        query: { supplierPers_idSupplier: <?php echo $this->supplier->supplier_idSupplier; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Supplier.supplierPersGridRowClick(this);
                    </script>
                </table>
            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button">
                    New Supplier Personnel
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Supplier.newSupplierPersButtonClick({
                            supplierPers_idSupplier : <?php echo $this->supplier->supplier_idSupplier; ?>
                        });
                    </script>
                </button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>