<?php
	$this->title = "BBA Supplier Update";
	$this->headTitle($this->title);
?>

<div class="form_wrap">
    <?php echo $this->supplierSaveForm; ?>
</div>

<div class="clear">&nbsp;</div>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Contacts',
    'label'     => 'New Contact',
    'location'  => $this->url(array(
        'controller'    => 'supplier-contact',
        'action'        => 'add'
    ),'default', true)
)); ?>

<div dojotype="dojox.data.QueryReadStore"
     jsid="contactStore"
     url="/supplier/supplier-contact-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="contactGrid"
       store="contactStore"
       query="{ supplierCo_idSupplier: <?php echo $this->supplier->idSupplier; ?> }"
       sortInfo="2"
       style="margin:auto;"
       autoWidth="false"
       autoHeight="20"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="supplierCo_idSupplierContact" width="75">Id</th>
            <th field="supplierCo_name" width="150">Name</th>
            <th field="supplierCo_phone" width="100">Phone</th>
            <th field="supplierCo_email" width="300">Email</th>
            <th field="supplierCo_address1" width="200">Address 1</th>
            <th field="supplierCo_postcode" width="auto">Postcode</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Contracts',
    'label'     => 'New Contract',
    'location'  => $this->url(array(
        'controller'    => 'contract',
        'action'        => 'add',
        'supplierId'    => $this->supplier->idSupplier
    ),'default', true)
)); ?>

<div dojotype="dojox.data.QueryReadStore"
     jsid="contractStore"
     url="/supplier/supplier-contract-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="contractGrid"
       store="contractStore"
       query="{ tender_idSupplier: <?php echo $this->supplier->idSupplier; ?> }"
       sortInfo="2"
       style="margin:auto;"
       autoWidth="false"
       autoHeight="20"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="contract_idContract" width="75">Id</th>
            <th field="contract_type" width="150">Type</th>
            <th field="contract_status" width="100">Status</th>
            <th field="contract_dateEnd" width="100">End Date</th>
            <th field="contract_reference" width="200">Reference</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>

