<?php $this->dojo()->requireModule('bba/Supplier', true); ?>
<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'"
         >
        <div class="tabHeading">
            <?php
                $this->title = "BBA Suppliers";
                $this->headTitle($this->title);

                echo $this->supplierSearchForm;
            ?>

            <div class="tableHead">
                <h2 class="tableHead-heading">Suppliers:</h2>
                <?php if ($this->isAllowed('User')): ?>
                <p class="tableHead-button">
                    <button data-dojo-type="dijit.form.Button">
                        New Supplier
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Supplier.newSupplierButtonClick();
                        </script>
                    </button>
                </p>
                <?php endif; ?>
            </div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div id="supplierGrid"></div>
    </div>
</div>