<?php
$form = $this->supplierContactSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="supplierCoForm"
     data-dojo-id="supplierCoForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Supplier Personnel Details',
        execute: bba.Supplier.processSupplierCoForm">
    <div class="dijitDialogPaneContentArea">

        <div class="dialog_title">
            
        </div>

        <div class="form_wrap">
            <div class="zend_form">

                <?php echo $form->supplierCo_type; ?>

                <?php echo $form->supplierCo_name; ?>

                <?php echo $form->supplierCo_position; ?>

                <?php echo $form->supplierCo_phone; ?>

                <?php echo $form->supplierCo_email; ?>

                <?php echo $form->supplierCo_address1; ?>

                <?php echo $form->supplierCo_address2; ?>

                <?php echo $form->supplierCo_address3; ?>

                <?php echo $form->supplierCo_postcode; ?>
                
                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>

                <input dojoType="dijit.form.TextBox"
                    type="hidden"
                    name="supplierCo_idSupplierContact"
                    id="supplierCo_idSupplierContact"
                    required="true"
                    value="<?php echo $form->supplierCo_idSupplierContact->getValue(); ?>" />

                <input data-dojo-type="dijit.form.TextBox"
                    type="hidden"
                    name="supplierCo_idSupplier"
                    id="supplierCo_idSupplier"
                    required="true"
                    value="<?php echo $form->supplierCo_idSupplier->getValue(); ?>" />

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return dijit.byId('supplierCoForm').validate();}"
                        type="submit"
                        id="supplierCoFormSubmitButton">Save</button>

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return bba.closeDialog(dijit.byId('supplierCoForm'));}"
                        id="supplierCoFormCancelButton">Cancel</button>
            </div>
        </div>
    </div>
</div>