<?php $this->dojo()->requireModule('bba/Invoice', true); ?>

<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">
        <div class="tabHeading">
             <?php
                $this->title = "BBA Invoices";
                $this->headTitle($this->title);

                echo $this->invoiceSearchForm;
            ?>

            <div class="tableHead">
                <h2 class="tableHead-heading">Invoices:</h2>
                <!--
                <p class="tableHead-button">
                    <button data-dojo-type="dijit.form.Button">
                        New Invoice
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Invoice.newInvoiceButtonClick();
                        </script>
                    </button>
                </p>
                -->
            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div id="invoiceGrid"></div>
    </div>
</div>