<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <span data-dojo-type="dojox.data.QueryReadStore"
        data-dojo-props="url: 'invoice/data-store/type/invoice-usage', requestMethod: 'post'"
        data-dojo-id="invoiceUsageStore<?php echo $this->invoiceLine->invoiceLine_idInvoiceLine; ?>"></span>

    <table data-dojo-type="dojox.grid.DataGrid"
        data-dojo-id="invoiceUsageGrid<?php echo $this->invoiceLine->invoiceLine_idInvoiceLine; ?>"
        id="invoiceUsageGrid<?php echo $this->invoiceLine->invoiceLine_idInvoiceLine; ?>"
        data-dojo-props='
            region: "center",
            store: invoiceUsageStore<?php echo $this->invoiceLine->invoiceLine_idInvoiceLine; ?>,
            structure: bba.Invoice.gridLayouts.invoiceUsage,
            query: { invoiceUsage_idInvoiceLine: <?php echo $this->invoiceLine->invoiceLine_idInvoiceLine; ?> },
            sortInfo: "-5",
            noDataMessage : bba.gridMessage'>
        <script type="dojo/method" data-dojo-event="onRowClick">
            bba.Invoice.invoiceUsageGridRowClick(this);
        </script>
    </table>
</div>