<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">
        <div class="tabHeading">

        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <span data-dojo-type="dojox.data.QueryReadStore"
              data-dojo-props="url: 'invoice/data-store/type/invoice-lines', requestMethod: 'post'"
              data-dojo-id="invoiceLinesStore<?php echo $this->invoice->invoice_idInvoice; ?>"></span>

        <table data-dojo-type="dojox.grid.DataGrid"
            data-dojo-id="invoiceLinesGrid<?php echo $this->invoice->invoice_idInvoice; ?>"
            id="invoiceLinesGrid<?php echo $this->invoice->invoice_idInvoice; ?>"
            data-dojo-props='
                store: invoiceLinesStore<?php echo $this->invoice->invoice_idInvoice; ?>,
                structure: bba.Invoice.gridLayouts.invoiceLines,
                query: { invoiceLine_idInvoice: <?php echo $this->invoice->invoice_idInvoice; ?> },
                sortInfo: "-1",
                noDataMessage : bba.gridMessage'>
            <script type="dojo/method" data-dojo-event="onRowClick">
                bba.Invoice.invoiceLinesGridRowClick(this);
            </script>
        </table>
    </div>
</div>