<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">
        <div class="tabHeading">
            <h2>Invoice Details</h2>

            <div>
                <p>
                    <b>Invoice Id:&nbsp;</b>
                    <?php echo $this->invoice->invoice_idInvoice; ?>
                </p>
                <p>
                    <b>Invoice No:&nbsp;</b>
                    <?php echo $this->invoice->invoice_numberInvoice; ?>
                </p>
                <p>
                    <b>Supplier:&nbsp;</b>
                    <?php echo $this->invoice->invoice_nameSupplier; ?>
                </p>
                <p>
                    <b>Invoice Date:&nbsp;</b>
                    <?php echo $this->invoice->invoice_dateInvoice; ?>
                </p>
            </div>
        </div>
    </div>

     <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'center'"
         class="invoiceEditTabs-BorderContainter">

        <div id="InvoiceTabs<?php echo $this->invoice->invoice_idInvoice; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true', splitter: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Invoice Lines'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'invoice/data-store/type/invoice-lines', requestMethod: 'post'"
                    data-dojo-id="invoiceLinesStore<?php echo $this->invoice->invoice_idInvoice; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    data-dojo-id="invoiceLinesGrid<?php echo $this->invoice->invoice_idInvoice; ?>"
                    id="invoiceLinesGrid<?php echo $this->invoice->invoice_idInvoice; ?>"
                    data-dojo-props='
                        store: invoiceLinesStore<?php echo $this->invoice->invoice_idInvoice; ?>,
                        structure: bba.Invoice.gridLayouts.invoiceLines,
                        query: { invoiceLine_idInvoice: <?php echo $this->invoice->invoice_idInvoice; ?> },
                        sortInfo: "-1",
                        noDataMessage : bba.gridMessage'>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Meter.meterGridRowClick(this);
                    </script>
                </table>
            </div>

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Invoice Usage'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                    data-dojo-props="url: 'invoice/data-store/type/invoice-usage', requestMethod: 'post'"
                    data-dojo-id="invoiceUsageStore<?php echo $this->invoice->invoice_idInvoice; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                    data-dojo-id="invoiceUsageGrid<?php echo $this->invoice->invoice_idInvoice; ?>"
                    id="invoiceUsageGrid<?php echo $this->invoice->invoice_idInvoice; ?>"
                    data-dojo-props='
                        store: invoiceUsageStore<?php echo $this->invoice->invoice_idInvoice; ?>,
                        structure: bba.Invoice.gridLayouts.invoiceUsage,
                        query: { invoiceLine_idInvoice: <?php echo $this->invoice->invoice_idInvoice; ?> },
                        sortInfo: "-1",
                        noDataMessage : bba.gridMessage'>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Meter.meterGridRowClick(this);
                    </script>
                </table>
            </div>
        </div>
    </div>
</div>