<?php
$this->dojo()->requireModule('bba/Core', true);
/* @var $error Exception */
$error = $this->message;
?>
<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'BBA System Error'" data-dojo-id="error" id="error">
    <div class="dijitDialogPaneContentArea">
        <div id="error-content">
            <table>
                <caption>There was an error processing your request, please report the following
                         message to your administrator:</caption>
                <tr>
                    <th>Error Code:</th>
                    <td><p class="errorMessage"><?php echo $error->getCode(); ?></p></td>
                </tr>
                <tr>
                    <th>File:</th>
                    <td><p class="errorMessage"><?php echo $error->getFile(); ?></p></td>
                </tr>
                <tr>
                    <th>Line:</th>
                    <td><p class="errorMessage"><?php echo $error->getLine(); ?></p></td>
                </tr>
                <tr>
                    <th>Message:</th>
                    <td><p class="errorMessage"><?php echo $error->getMessage(); ?></p></td>
                </tr>
                <tr>
                    <th>Trace:</th>
                    <td>
                        <p class="errorMessage">
                            <pre><?php echo $error->getTraceAsString(); ?></pre>
                        </p>
                    </td>
                </tr>
            </table>
        </div>
        <button data-dojo-type="dijit.form.Button">
            Close
            <script type="dojo/method" data-dojo-event="onClick">
                return bba.closeDialog(error);
            </script>
        </button>
        <button data-dojo-type="dijit.form.Button">
            Home Page
            <script type="dojo/method" data-dojo-event="onClick">
                window.location = "<?php echo $this->baseUrl(); ?>/";
                return bba.closeDialog(error);
            </script>
        </button>
    </div>
    <script type="dojo/method" data-dojo-event="onHide">
    	return bba.closeDialog(error);
    </script>
</div>