<?php echo $this->docType(); ?>
<html lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link rel="stylesheet" href="/css/reset.css" />
        <link rel="stylesheet" href="/css/text.css" />

        <?php echo $this->headLink() ?>

        <?php echo $this->dojo(); ?>

        <script type="text/javascript" src="/js/bba/Core.js"></script>
        <script type="text/javascript" src="/js/bba/ContentPane.js"></script>
        <script type="text/javascript" src="/js/bba/StackContainer.js"></script>
        <script type="text/javascript" src="/js/bba/DataGrid.js"></script>

        <link rel="stylesheet" href="/css/site.css" />

        <?php echo $this->headScript() ?>
    </head>
    <body class="claro">
        <div id="loader">
            <div id="loaderInner"></div>
        </div>
        <div id="appLayout"
         data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'sidebar'">

        <?php if ($this->authInfo('role')): ?>
        <div id="ContentTabs"
             class="centerPanel"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'">
        <?php endif; ?>
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: '<?php echo $this->escape($this->title); ?>'"
                 id="<?php echo $this->getRequest()->getControllerName(); ?>-list">
                <div id="messages"><?php
                   echo $this->FlashMessenger();
                 ?></div>

                <?php echo $this->Layout()->content; ?>
            </div>
         <?php if ($this->authInfo('role')): ?>
         </div>
         <?php endif; ?>

        <?php if ($this->authInfo('role')): ?>
        <div id="topPanel" class="edgePanel"
             data-dojo-type="dijit.layout.ContentPane"
             data-dojo-props="region: 'top'">
             <h1>BBA Power Data Base System</h1>
        </div>

        <div id="leftPanel" class="edgePanel"
            data-dojo-type="dijit.layout.ContentPane"
            data-dojo-props="region: 'left', splitter: true">
            <div>
                <p>User Name: <?php echo $this->authInfo('name'); ?></p>
                <p>Role: <?php echo $this->authInfo('role'); ?></p>
            </div>

            <div id="nav">
                <?php echo $this->navigation()->sfMenu(); ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
    </body>
</html>