<?php echo $this->docType(); ?>
<html lang="en">
    <head>
        <base href="<?php echo $this->baseUrl(); ?>/" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('css/reset.css'); ?>" type="text/css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('css/text.css'); ?>" type="text/css" />
        
        <script type="text/javascript">
           var bbaModule = '<?php echo ucfirst($this->request()->getControllerName()); ?>';
        </script>

        <?php echo $this->headLink() ?>

        <?php echo $this->dojo(); ?>

        <link rel="stylesheet" href="<?php echo $this->baseUrl('css/site.css'); ?>" type="text/css" />
    </head>
    <body class="claro">
        <div id="loader">
            <div id="loaderInner"></div>
        </div>
        <div id="appLayout"
         data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline'">

        <?php if ($this->authInfo('role')): ?>
        <div id="ContentTabs"
             class="centerPanel"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'">
        <?php endif; ?>
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: '<?php echo $this->escape($this->title); ?>'"
                 id="<?php echo $this->request()->getControllerName(); ?>-list">
          		
                <?php echo $this->Layout()->content; ?>
            </div>
         <?php if ($this->authInfo('role')): ?>
         </div>
         <?php endif; ?>

        <?php if ($this->authInfo('role')): ?>
        <div id="topPanel" class="edgePanel"
             data-dojo-type="dijit.layout.ContentPane"
             data-dojo-props="region: 'top'">
             <h1>BBA Power Data Base System </h1>
             <span id="version"><?php echo $this->version(); ?></span>
             <span id="dojoVersion"></span>
        </div>

        <div id="leftPanel" class="edgePanel"
            data-dojo-type="dijit.layout.ContentPane"
            data-dojo-props="region: 'left', splitter: false">
            <div id="leftPanelTop">
                <p>User: <?php echo $this->authInfo('user_fullName'); ?></p>
                <p>Role: <?php echo $this->authInfo('user_role'); ?></p>
            </div>

            <div id="nav">
                <?php echo $this->navigation()->sfMenu(); ?>
            </div>

            <div id="leftPanelBottom">
                <p><button data-dojo-type="dijit.form.ToggleButton"
                           data-dojo-props="iconClass:'dijitCheckBoxIcon'"
                           id="tabRefreshButton">
                    Tab Refresh
                    <script type="dojo/method" data-dojo-event="onChange" data-dojo-args="val">
                        bba.setPref(this, val);
                    </script>
                </button></p>
                <p><button data-dojo-type="dijit.form.ToggleButton"
                           data-dojo-props="iconClass:'dijitCheckBoxIcon', checked: true"
                           id="confirmBoxButton">
                    Confirmation
                    <script type="dojo/method" data-dojo-event="onChange" data-dojo-args="val">
                        bba.setPref(this, val);
                    </script>
                </button></p>
                <p><button data-dojo-type="dijit.form.Button"
                           id="clearCacheButton">
                    Clear Cache
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.clearCache();
                    </script>
                </button></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div id="dialog"></div>
    <div id="errorDialog"></div>
    <div data-dojo-id="pageStandby"
     	 data-dojo-type="dojox.widget.Standby"
     	 data-dojo-props="target:'ContentTabs', color: '#efefef', image: 'images/loader_lg.gif'"></div>
    </body>
</html>