<?php echo $this->docType(); ?>
<html lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta http-equiv=“X-UA-Compatible” content=“IE=edge” />
        <link rel="stylesheet" href="/css/reset.css" />
        <link rel="stylesheet" href="/css/text.css" />

        <?php echo $this->headLink() ?>

        <?php echo $this->dojo()->enable(); ?>

        <link rel="stylesheet" href="/css/site.css" />

        <?php echo $this->headScript() ?>
        <script>
            dojo.addOnLoad(function(){

                if (dijit.registry.length == 0) {
                    dojo.parser.parse();
                }

                var loader = dojo.byId("loader");
                loader.style.display = "none";

			});
        </script>

    </head>
    <body class="claro">
        <div id="loader">
            <div id="loaderInner"></div>
        </div>
        <div id="appLayout"
         data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'sidebar'">

        <div class="centerPanel"
             data-dojo-type="dijit.layout.ContentPane"
             data-dojo-props="region: 'center'">

                <div id="messages"><?php
                   echo $this->FlashMessenger();
                 ?></div>
                <h1><?php echo $this->escape($this->title); ?></h1>
                <?php echo $this->Layout()->content; ?>
        </div>

        <?php if ($this->authInfo('role')): ?>
        <div id="topPanel" class="edgePanel"
             data-dojo-type="dijit.layout.ContentPane"
             data-dojo-props="region: 'top'">
             <h1>BBA Power Data Base System</h1>
        </div>

        <div id="leftPanel" class="edgePanel"
            data-dojo-type="dijit.layout.ContentPane"
            data-dojo-props="region: 'left', splitter: true">
            <div>
                <p>User Name: <?php echo $this->authInfo('name'); ?></p>
                <p>Role: <?php echo $this->authInfo('role'); ?></p>
            </div>

            <div id="nav">
                <?php echo $this->navigation()->sfMenu(); ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
    </body>
</html>