<button dojoType="dijit.form.Button"
        id="addMeterToContractButton"
        type="button"
        onClick="bba.Contract.addMeterToContract(contractMeterGrid, <?php echo $this->contract->contract_idContract; ?>);">
    Update Contract
</button>

<button dojoType="dijit.form.Button"
        id="selectAllButton"
        type="button"
        onClick="bba.Contract.selectAll(contractMeterGrid)">
    Select All Meters
</button>

<button data-dojo-type="dijit.form.Button"
        data-dojo-props="type: 'button'"
        id="cancelButton">
    Cancel
    <script type="dojo/method" data-dojo-event="onClick">
        bba.closeDialog(addMeterContractDialog);
    </script>
</button>

<img id="contractMeterHelp" src="images/help.png" />

<div dojoType="dijit.Tooltip" connectId="contractMeterHelp">
    <p>
        Select meters to add by clicking on the row or the row selector on the left of the row.<br />
        To deselect a meter click on the row again or the row selector on the left of the row.<br />
        Edit "Expected Yearly Consumption" by double clicking on the cell.<br />
        When a row is selected it will be light blue in colour.<br />
        When you are ready to add meters click the "Add to Contract" button.
    </p>
</div>
<div>&nbsp;</div>

<span data-dojo-type="dojo.data.ItemFileWriteStore"
        data-dojo-props="url: 'contract/data-store/type/availableMeters/meterContract_idContract/<?php echo $this->contract->contract_idContract; ?>', requestMethod: 'post'"
        data-dojo-id="contractMeterStore"></span>

<div data-dojo-type="dojox.grid.DataGrid"
        data-dojo-id="contractMeterGrid"
        data-dojo-props="
        store: contractMeterStore,
        structure: bba.Contract.gridLayouts.meterContract,
        query: { meter_idMeter : '*' },
        clientSort: 'true',
        selectionMode: 'multiple',
        editable: 'true',
        sortInfo: '-6',
        noDataMessage : bba.gridMessage,
        style: 'width:1100px;height:300px;'">
    <script type="dojo/connect" event="_onFetchComplete" args="items, req">
        bba.Contract.preselectMeters(this, '<?php echo $this->contract->contract_idContract; ?>', items);
        <?php if ($this->contract->contract_status == 'tender'): ?>
            dijit.byId('tenderWarningDialog').show();
        <?php endif; ?>
    </script>
</div>

<div dojoType="dijit.Dialog" id="tenderWarningDialog" title="Tender Warning">
    <div class="dijitDialogPaneContentArea" style="text-align: center;">
        <img src="images/Warning.png" />
        <p>
            <b>After editing meters the tenders<br />
            will need re-submitting.</b>
        </p>
    </div>
    <div class="dijitDialogPaneActionBar">
        <button dojoType="dijit.form.Button" type="button" onClick="dijit.byId('tenderWarningDialog').hide();">
            OK
        </button>
    </div>
</div>
