<?php $form = $this->contractSaveForm; ?>

<div class="form_wrap">
    <div id="contractForm" class="zend_form">

        <?php if ($this->request()->getParam('type') == 'edit'): ?>
            <?php echo $form->client; ?>
            <input dojoType="dijit.form.TextBox"
                   type="hidden"
                   name="contract_idClient"
                   id="contract_idClient"
                   required="true"
                   value="<?php echo $form->contract_idClient->getValue(); ?>" />
        <?php else: ?>
            <?php echo $form->contract_idClient; ?>
        <?php endif; ?>

        <?php echo $form->contract_idTenderSelected ?>

        <?php echo $form->contract_reference; ?>

        <?php echo $form->contract_numberCustomer; ?>

        <?php echo $form->contract_type; ?>

        <?php echo $form->contract_status; ?>

        <?php echo $form->contract_dateStart; ?>

        <?php echo $form->contract_dateEnd; ?>

        <?php echo $form->contract_periodBill; ?>

        <?php echo $form->contract_desc; ?>

        <?php echo $form->contract_txtTenderRequest; ?>

        <?php echo $form->contract_docAnalysis; ?>

        <?php echo $form->contract_docTermination; ?>

        <input dojoType="dijit.form.TextBox"
               type="hidden"
               name="contract_idContract"
               id="contract_idContract"
               required="true"
               value="<?php echo $form->contract_idContract->getValue(); ?>" />

        <input dojoType="dijit.form.TextBox"
               type="hidden"
               name="contract_idContractPrevious"
               id="contract_idContractPrevious"
               required="true"
               value="<?php echo $form->contract_idContractPrevious->getValue(); ?>" />

        <button dojoType="dijit.form.Button"
                type="submit"
                id="contractFormSubmitButton"
                name="submit"
                value="Save">Save</button>

        <button dojoType="dijit.form.Button"
                type="button"
                id="contractFormCancelButton"
                name="cancel"
                value="Cancel">Cancel</button>
    </div>
</div>