<?php
$form = $this->contractSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="contractForm"
     data-dojo-id="contractForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Contract',
        execute: bba.Contract.processContractForm">
    <div class="dijitDialogPaneContentArea">
        <div class="form_wrap">
            <div id="contractForm" class="zend_form">

                <?php if ($form->contract_idClient->getValue()): ?>
                    <?php echo $form->client_contract; ?>
                    <input dojoType="dijit.form.TextBox"
                           type="hidden"
                           name="contract_idClient"
                           id="contract_idClient"
                           required="true"
                           value="<?php echo $form->contract_idClient->getValue(); ?>" />
                <?php else: ?>
                    <?php echo $form->contract_idClient; ?>
                <?php endif; ?>

                <?php echo $form->contract_idTenderSelected ?>

                <?php  if ($this->request()->getParam('type') == 'add'): ?>
                    <?php echo $form->contract_type; ?>
                <?php else: ?>
                    <div class="form_row">
                        <p id="contract_type-edit-label">
                            <label class="optional" for="contract_type">Type:</label>
                        </p>
                        <p class="element">
                            <?php echo $form->contract_type->getValue(); ?>
                            <input dojoType="dijit.form.TextBox"
                                   type="hidden"
                                   name="contract_type"
                                   id="contract_type"
                                   required="true"
                                   value="<?php echo $form->contract_type->getValue(); ?>" />
                        <p/>
                    </div>
                <?php endif; ?>

                <?php echo $form->contract_status; ?>

                <?php echo $form->contract_dateStart; ?>

                <?php echo $form->contract_dateEnd; ?>

                <?php echo $form->contract_reference; ?>

                <?php echo $form->contract_numberCustomer; ?>

                <?php echo $form->contract_periodBill; ?>

                <?php echo $form->contract_desc; ?>

                <?php echo $form->contract_txtTenderRequest; ?>

                <?php echo $form->contract_docAnalysis; ?>

                <?php echo $form->contract_docTermination; ?>

                <input dojoType="dijit.form.TextBox"
                       type="hidden"
                       name="type"
                       id="type"
                       required="true"
                       value="<?php echo $this->request()->getParam('type'); ?>" />

                <input dojoType="dijit.form.TextBox"
                       type="hidden"
                       name="contract_idContract"
                       id="contract_idContract"
                       required="true"
                       value="<?php echo $form->contract_idContract->getValue(); ?>" />

                <input dojoType="dijit.form.TextBox"
                       type="hidden"
                       name="contract_idContractPrevious"
                       id="contract_idContractPrevious"
                       required="true"
                       value="<?php echo $form->contract_idContractPrevious->getValue(); ?>" />

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return dijit.byId('contractForm').validate();}"
                        type="submit"
                        id="contractFormSubmitButton">Save</button>

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return bba.closeDialog(dijit.byId('contractForm'));}"
                        id="contractFormCancelButton">Cancel</button>
            </div>
        </div>
    </div>

</div>