<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Tender Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->tender->tender_idTender; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('User')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Contract.editTenderButtonClick({
                                    tender_idTender : <?php echo $this->tender->tender_idTender; ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Supplier:</th>
                    <td><?php echo $this->tender->getSupplier('supplier_name'); ?></td>
                </tr>
                <tr>
                    <th>Supplier Liaison:</th>
                    <td><?php echo $this->tender->getSupplierPersonnel('supplierPers_name'); ?></td>
                </tr>
                <tr>
                    <th>Reference:</th>
                    <td><?php echo $this->tender->tender_reference; ?></td>
                </tr>
                <tr>
                    <th>Tender Period:</th>
                    <td><?php echo $this->tender->tender_periodContract; ?></td>
                </tr>
                <tr>
                    <th>Expiry Date:</th>
                    <td><?php echo $this->formatDate($this->tender->tender_dateExpiresQuote); ?></td>
                </tr>
                <tr>
                    <th>Standing Charge:</th>
                    <td><?php echo $this->tender->tender_chargeStanding; ?></td>
                </tr>
                <tr>
                    <th>Unit Price Day:</th>
                    <td><?php echo $this->tender->tender_priceUnitDay; ?></td>
                </tr>
                <tr>
                    <th>Unit Price Night:</th>
                    <td><?php echo $this->tender->tender_priceUnitNight; ?></td>
                </tr>
                <tr>
                    <th>Unit Price Other:</th>
                    <td><?php echo $this->tender->tender_priceUnitOther; ?></td>
                </tr>
                <tr>
                    <th>Capacity Charge:</th>
                    <td><?php echo $this->tender->tender_chargeCapacity; ?></td>
                </tr>
                <tr>
                    <th>Settlement Charge:</th>
                    <td><?php echo $this->tender->tender_chargeSettlement; ?></td>
                </tr>
                <tr>
                    <th>Commission Rate:</th>
                    <td><?php echo $this->tender->tender_commission." (Pence / Unit)";?></td>
                </tr>
                <tr>
                    <th>Commission Fee:</th>
                    <td><?php echo $this->tender->tender_fee." (£ / Year)";?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>&nbsp;</caption>
                <tr>
                    <th>Client:</th>
                    <td><?php echo $this->tender->getContract()->getClient('client_name'); ?></td>
                </tr>
                <tr>
                    <th>Contract Ref:</th>
                    <td><?php echo $this->tender->getContract('contract_reference'); ?></td>
                </tr>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->tender->getContract('contract_type'); ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->tender->getContract('contract_status'); ?></td>
                </tr>
                <tr>
                    <th>Start Date:</th>
                    <td><?php echo $this->formatDate($this->tender->getContract('contract_dateStart')); ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>&nbsp;</caption>
                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->tender->getShortDesc(); ?></td>
                </tr>
            </table>

            <div class="clear"></div>
        </div>
    </div>
</div>
