<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top', splitter: 'true'">

        <div class="tabHeading">
            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Contract Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->contract->contract_idContract; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('User')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Contract.editContractButtonClick({
                                    contract_idContract : <?php echo $this->contract->contract_idContract; ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->contract->getContractType(); ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->contract->getContractStatus(); ?></td>
                </tr>
                <tr>
                    <th>Start Date:</th>
                    <td><?php echo $this->formatDate($this->contract->contract_dateStart); ?></td>
                </tr>
                <tr>
                    <th>End Date:</th>
                    <td><?php echo $this->formatDate($this->contract->contract_dateEnd); ?></td>
                </tr>
                <tr>
                    <th>Reference:</th>
                    <td><?php echo $this->contract->contract_reference; ?></td>
                </tr>
                <?php if ($this->contract->contract_idTenderSelected): ?>
                <tr>
                    <th>Tender Selected:</th>
                    <td><?php echo $this->contract->contract_idTenderSelected; ?></td>
                </tr>
                <tr>
                    <th>Supplier Name:</th>
                    <td><?php echo $this->contract->getTenderSelected()->getSupplier('supplier_name'); ?></td>
                </tr>
                <tr>
                    <th>Contract Period:</th>
                    <td><?php echo $this->contract->getTenderSelected('tender_periodContract'); ?> Months</td>
                </tr>
                <tr>
                    <th>Commission Rate:</th>
                    <td><?php echo $this->contract->getTenderSelected('tender_commission'); ?> (Pence / Unit)</td>
                </tr>
                <tr>
                    <th>Commission Fee:</th>
                    <td><?php echo $this->contract->getTenderSelected('tender_fee'); ?> (&pound; / Year)</td>
                </tr>
                <?php else: ?>
                <tr>
                    <td colspan="2">- No Tender Has Been Selected -</td>
                </tr>
                <?php endif; ?>
            </table>

            <table class="info_wrap ident">
                <caption>&nbsp;</caption>
                <tr>
                    <th>Client:</th>
                    <td><?php echo $this->contract->getClient('client_name'); ?></td>
                </tr>
                <tr>
                    <th>Customer Number:</th>
                    <td><?php echo $this->contract->contract_numberCustomer; ?></td>
                </tr>
                <tr>
                    <th>Billing Period:</th>
                    <td><?php echo $this->contract->contract_periodBill; ?> (months)</td>
                </tr>
                <tr>
                    <th>Tender Decision Date:</th>
                    <td><?php echo $this->formatDate($this->contract->contract_dateDecision); ?></td>
                </tr>
                <tr>
                    <th>Analysis Doc:</th>
                    <td>
                        <?php echo $this->DocAnalysis($this->contract)->getCurrentFile(); ?>
                        <?php if ($files = $this->DocAnalysis($this->contract)->getFileList()): ?><br />
                        <a href="#" onClick="dijit.byId('contractDocAnalysis<?php echo $this->contract->contract_idContract; ?>FileList').show(); return false;">
                            Show All ...
                        </a>
                        <?php
                            echo $this->partial('filelist.phtml', array(
                                'row' => $this->contract,
                                'files' => $files,
                                'id' => 'DocAnalysis' . $this->contract->contract_idContract,
                                'controller' => 'contract',
                                'docClass'   => 'DocAnalysis'
                            ));
                        ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Contract (Searchable) Doc:</th>
                    <td>
                        <?php echo $this->DocContractSearchable($this->contract)->getCurrentFile(); ?>
                        <?php if ($files = $this->DocContractSearchable($this->contract)->getFileList()): ?><br />
                        <a href="#" onClick="dijit.byId('contractDocContractSearchable<?php echo $this->contract->contract_idContract; ?>FileList').show(); return false;">
                            Show All ...
                        </a>
                        <?php
                            echo $this->partial('filelist.phtml', array(
                                'row' => $this->contract,
                                'files' => $files,
                                'id' => 'DocContractSearchable' . $this->contract->contract_idContract,
                                'controller' => 'contract',
                                'docClass'   => 'DocContractSearchable'
                            ));
                        ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Contract (Client Signed) Doc:</th>
                    <td>
                        <?php echo $this->DocContractSignedClient($this->contract)->getCurrentFile(); ?>
                        <?php if ($files = $this->DocContractSignedClient($this->contract)->getFileList()): ?><br />
                        <a href="#" onClick="dijit.byId('contractDocContractSignedClient<?php echo $this->contract->contract_idContract; ?>FileList').show(); return false;">
                            Show All ...
                        </a>
                        <?php
                            echo $this->partial('filelist.phtml', array(
                                'row' => $this->contract,
                                'files' => $files,
                                'id' => 'DocContractSignedClient' . $this->contract->contract_idContract,
                                'controller' => 'contract',
                                'docClass'   => 'DocContractSignedClient'
                            ));
                        ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Contract (Both Signed) Doc:</th>
                    <td>
                        <?php echo $this->DocContractSignedBoth($this->contract)->getCurrentFile(); ?>
                        <?php if ($files = $this->DocContractSignedBoth($this->contract)->getFileList()): ?><br />
                        <a href="#" onClick="dijit.byId('contractDocContractSignedBoth<?php echo $this->contract->contract_idContract; ?>FileList').show(); return false;">
                            Show All ...
                        </a>
                        <?php
                            echo $this->partial('filelist.phtml', array(
                                'row' => $this->contract,
                                'files' => $files,
                                'id' => 'DocContractSignedBoth' . $this->contract->contract_idContract,
                                'controller' => 'contract',
                                'docClass'   => 'DocContractSignedBoth'
                            ));
                        ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Termination Doc:</th>
                    <td>
                        <?php echo $this->DocTermination($this->contract)->getCurrentFile(); ?>
                        <?php if ($files = $this->DocTermination($this->contract)->getFileList()): ?><br />
                        <a href="#" onClick="dijit.byId('contractDocTermination<?php echo $this->contract->contract_idContract; ?>FileList').show(); return false;">
                            Show All ...
                        </a>
                        <?php
                            echo $this->partial('filelist.phtml', array(
                                'row' => $this->contract,
                                'files' => $files,
                                'id' => 'DocTermination' . $this->contract->contract_idContract,
                                'controller' => 'contract',
                                'docClass'   => 'DocTermination'
                            ));
                        ?>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>&nbsp;</caption>
                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->contract->getShortDesc(); ?></td>
                </tr>
            </table>
        </div>

    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'center'"
         class="contractEditTabs-BorderContainter">

        <div id="ContractTabs<?php echo $this->contract->contract_idContract; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true', tabPosition: 'top'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Meters'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-id="contractMeterStore<?php echo $this->contract->contract_idContract; ?>"
                      data-dojo-props="url:'contract/data-store/type/meter',requestMethod:'post'"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       id="meterContractGrid<?php echo $this->contract->contract_idContract; ?>"
                       data-dojo-props="
                        store: contractMeterStore<?php echo $this->contract->contract_idContract; ?>,
                        structure: bba.Contract.gridLayouts.meter,
                        query: { meterContract_idContract: <?php echo $this->contract->contract_idContract; ?> },
                        sortInfo: '3',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Meter.meterGridRowClick(this);
                    </script>
                </table>
            </div>

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Tenders'">

                 <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-id="tenderStore<?php echo $this->contract->contract_idContract; ?>"
                      data-dojo-props="url:'contract/data-store/type/tender',requestMethod:'post'"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       id="tenderGrid<?php echo $this->contract->contract_idContract; ?>"
                       data-dojo-props="
                        store: tenderStore<?php echo $this->contract->contract_idContract; ?>,
                        structure: bba.Contract.gridLayouts.tender,
                        query: { tender_idContract: <?php echo $this->contract->contract_idContract; ?> },
                        sortInfo: '-6',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Contract.tenderGridRowClick(this);
                    </script>
                </table>
            </div>

            <?php if ($this->isAllowed('Admin')): ?>
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="title: 'Invoice Lines'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'invoice/data-store/type/invoice-lines', requestMethod: 'post'"
                      data-dojo-id="contractInvoiceLinesStore<?php echo $this->contract->contract_idContract; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="contractInvoiceLinesGrid<?php echo $this->contract->contract_idContract; ?>"
                       id="contractInvoiceLinesGrid<?php echo $this->contract->contract_idContract; ?>"
                       data-dojo-props='
                           store: contractInvoiceLinesStore<?php echo $this->contract->contract_idContract; ?>,
                           structure: bba.Contract.gridLayouts.invoiceLines,
                           query: { invoiceLine_idContract: <?php echo $this->contract->contract_idContract; ?> },
                           sortInfo: "-3",
                           noDataMessage : bba.gridMessage'>
                    <script type="dojo/method" data-dojo-event="onCellClick" args="e">
                        var colField = e.cell.field
                        bba.Invoice.invoiceLineGridRowClick(this, e, colField);
                    </script>
                </table>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'"
         class="tableHeadPane">

        <div class="tableHead">
        	<?php $notAllowed = array('current', 'roledon', 'lapsed', 'dead'); ?>
            <?php if ($this->isAllowed('User')): ?>
            <?php if (!in_array($this->contract->contract_status, $notAllowed)): ?>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button">
                    Add/Edit Meters
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Contract.addMeterButtonClick({
                            contract_idContract : <?php echo $this->contract->contract_idContract; ?>
                        });
                    </script>
                </button>

            </p>
            <?php endif; ?>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button">
                    New Tender
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Contract.newTenderButtonClick({
                            tender_idContract : <?php echo $this->contract->contract_idContract; ?>
                        });
                    </script>
                </button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>