<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <div class="tabHeading">
             <table class="info_wrap">
                 <caption>Contract Details <span class="id_number">(<?php echo $this->contract->contract_idContract; ?>)</span></caption>
                <tr>
                    <th>Client:</th>
                    <td><?php echo $this->contract->getClient('client_name'); ?></td>
                </tr>
                <?php if ($this->contract->getContractPrevious()): ?>
                <tr>
                    <th>Previous Contract Ref:</th>
                    <td><?php echo $this->escape(
                        $this->previousContract->reference
                    ); ?></td>
                </tr>
                <tr>
                    <th>Previous End Date:</th>
                    <td><?php echo $this->escape(
                        $this->previousContract->dateEnd->toString('dd/MM/yyyy')
                    ); ?></td>
                </tr>
                <?php else: ?>
                <tr>
                    <th>Previous Contract:</th>
                    <td>No Previous Contract</td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Type:</th>
                    <td><?php echo $this->contract->contract_type; ?></td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?php echo $this->contract->contract_status; ?></td>
                </tr>
                <?php if ($this->contract->contract_idTenderSelected): ?>
                <tr>
                    <th>Tender Selected:</th>
                    <td><?php echo $this->contract->contract_idTenderSelected; ?></td>
                </tr>
                <tr>
                    <th>Supplier Name:</th>
                    <td><?php echo $this->contract->getTenderSelected()->getSupplier('supplier_name'); ?></td>
                </tr>
                <tr>
                    <th>Contract Period:</th>
                    <td><?php echo $this->contract->getTenderSelected('tender_periodContract'); ?> Months</td>
                </tr>
                <?php endif; ?>

                <?php if ($this->isAllowed('User')): ?>
                <tr>
                    <td class="footer" colspan="2">
                        <div dojoType="dijit.form.Form"
                             id="edit-contract-<?php echo $this->contract->contract_idContract; ?>">
                            <button data-dojo-type="dijit.form.Button"
                                    data-dojo-props="onClick: bba.Contract.editContractButtonClick"
                                    type="button"
                                    value="<?php echo $this->contract->contract_idContract; ?>"
                                    id="edit-contract-button-<?php echo $this->contract->contract_idContract; ?>">Edit Details</button>
                        </div>
                    </td>
                </tr>
                <?php endif; ?>
            </table>

            <table class="info_wrap ident">
                <caption>&nbsp;</caption>
                <tr>
                    <th>Start Date:</th>
                    <td><?php echo $this->formatDate($this->contract->contract_dateStart); ?></td>
                </tr>
                <tr>
                    <th>End Date:</th>
                    <td><?php echo $this->formatDate($this->contract->contract_dateEnd); ?></td>
                </tr>
                <tr>
                    <th>Reference:</th>
                    <td><?php echo $this->contract->contract_reference; ?></td>
                </tr>
                <tr>
                    <th>Customer Number:</th>
                    <td><?php echo $this->contract->contract_numberCustomer; ?></td>
                </tr>
                <tr>
                    <th>Bill Period:</th>
                    <td><?php echo $this->contract->contract_periodBill; ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>&nbsp;</caption>
                <tr>
                    <th>Description:</th>
                    <td class="description"><?php echo $this->contract->contract_desc; ?></td>
                </tr>
            </table>
        </div>

    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="contractEditTabs-BorderContainter">

        <div id="ContractTabs<?php echo $this->contract->contract_idContract; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true', tabPosition: 'top'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Meters'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-id="meterContractStore<?php echo $this->contract->contract_idContract; ?>"
                      data-dojo-props="url:'/contract/data-store/type/meter',requestMethod:'post'"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       id="meterContractGrid<?php echo $this->contract->contract_idContract; ?>"
                       data-dojo-props="
                        store: meterContractStore<?php echo $this->contract->contract_idContract; ?>,
                        structure: bba.Contract.gridLayouts.meter,
                        query: { meterContract_idContract: <?php echo $this->contract->contract_idContract; ?> },
                        sortInfo: '-3',
                        noDataMessage : bba.gridMessage,
                        onRowClick: bba.Meter.meterGridRowClick">
                </table>
            </div>

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Tenders'">

                 <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-id="tenderStore<?php echo $this->contract->contract_idContract; ?>"
                      data-dojo-props="url:'/contract/data-store/type/tender',requestMethod:'post'"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       id="tenderGrid<?php echo $this->contract->contract_idContract; ?>"
                       data-dojo-props="
                        store: tenderStore<?php echo $this->contract->contract_idContract; ?>,
                        structure: bba.Contract.gridLayouts.tender,
                        query: { tender_idContract: <?php echo $this->contract->contract_idContract; ?> },
                        sortInfo: '-3',
                        noDataMessage : bba.gridMessage,
                        onRowClick: bba.Contract.tenderGridRowClick">
                </table>

            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">

        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: bba.Contract.addMeterButtonClick"
                        type="button"
                        value="<?php echo $this->contract->contract_idContract; ?>"
                        id="add-meter-button-<?php echo $this->contract->contract_idContract; ?>">Add/Edit Meters</button>

            </p>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: bba.Contract.newTenderButtonClick"
                        type="button"
                        value="<?php echo $this->contract->contract_idContract; ?>"
                        id="new-tender-button-<?php echo $this->contract->contract_idContract; ?>">New Tender</button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>