<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <div class="form_wrap zend_form contract_edit ident alpha"
                 dojoType="dijit.form.Form"
                 id="edit-tender-<?php echo $this->tender->tender_idTender; ?>">
                <h3>Tender Details</h3>
                <div class="form_row">
                    <p class="label"><b>Supplier:</b></p>
                    <p>&nbsp;<?php echo $this->tender->getSupplier('supplier_name'); ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Tender Period:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_periodContract; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Expiry Date:</b></p>
                    <p>&nbsp;<?php echo $this->formatDate($this->tender->tender_dateExpiresQuote); ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Standing Charge:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_chargeStanding; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Unit Price Day:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_priceUnitDay; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Unit Price Night:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_priceUnitNight; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Unit Price Other:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_priceUnitOther; ?></p>
                </div>
                 <div class="form_row">
                    <p class="label"><b>Charge KVA:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_chargeKva; ?></p>
                </div>
                 <div class="form_row">
                    <p class="label"><b>Commission:</b></p>
                    <p>&nbsp;<?php echo $this->tender->tender_commission; ?></p>
                </div>

                <?php if ($this->isAllowed('User')): ?>
                <button dojoType="dijit.form.Button"
                    type="submit"
                    name="edit-tender-button-<?php echo $this->tender->tender_idTender; ?>"
                    value="submit">Edit Details</button>
                <?php endif; ?>
            </div>

            <div class="ident">
                <p><b>Client:</b> <?php echo $this->tender->getContract()->getClient('client_name'); ?></p>
                <p><b>Contract Ref:</b> <?php echo $this->tender->getContract('contract_reference'); ?></p>
                <p><b>Type:</b> <?php echo $this->tender->getContract('contract_type'); ?></p>
                <p><b>Status:</b> <?php echo $this->tender->getContract('contract_status'); ?></p>
                <p><b>Start Date:</b> <?php echo $this->formatDate($this->tender->getContract('contract_dateStart')); ?></p>
            </div>

            <div class="clear"></div>
        </div>
    </div>
</div>
