<?php
	$this->title = "BBA Contract Update";
	$this->headTitle($this->title);

    echo $this->contractSaveForm;
    /* @var $meter Power_Model_Meter */
?>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Meters',
    'label'     => 'New Meter',
    'location'  => $this->url(array(
        'controller'    => 'contract',
        'action'        => 'add-meter',
        'contractId'    => $this->contract->id
    ),'default', true)
)); ?>

<table>
    <thead>
        <tr>
            <th field="type">Type <span class="id">(id)</span></th>
            <th>Number Serial</th>
            <th>Number Main</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
<?php
	if ($this->meters):
		foreach($this->meters as $meter):
?>
    <tr>
        <td><?php echo $meter->type; ?>&nbsp;
            <span class="id">(<?php echo $this->escape($meter->id); ?>)</span></td>
        <td><?php echo $meter->numberSerial; ?></td>
        <td><?php echo $meter->numberMain; ?></td>
        <td class="action">

        </td>
    </tr>
<?php endforeach;
else: ?>
    <tr>
        <td colspan="4">This Contract has no meters yet.</td>
    </tr>
<?php endif; ?>
</table>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Tenders',
    'label'     => 'New Tender',
    'location'  => $this->url(array(
        'controller'    => 'contract',
        'action'        => 'add-tender',
        'contractId'    => $this->contract->id
    ),'default', true)
)); ?>

<table>
    <thead>
        <tr>
            <th>Contract Period <span class="id">(id)</span></th>
            <th>Quote Expires</th>
            <th>Standing Charge</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
<?php
	if ($this->tenders):
		foreach($this->tenders as $tender):
?>
    <tr>
        <td><?php echo $tender->periodContract; ?>&nbsp;
            <span class="id">(<?php echo $this->escape($tender->id); ?>)</span></td>
        <td><?php echo $tender->dateExpiresQuote; ?></td>
        <td><?php echo $tender->chargeStanding; ?></td>
        <td class="action">

        </td>
    </tr>
<?php endforeach;
else: ?>
    <tr>
        <td colspan="4">This Contract has no tenders yet.</td>
    </tr>
<?php endif; ?>
</table>