<?php
	$this->title = "BBA Contracts";
	$this->headTitle($this->title);

    echo $this->contractSearchForm;
    /* @var $meter Power_Model_Meter */

?>
<script>
    var contractStore = <?php echo $this->store; ?>;
    //onRowDblClick(e)
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowDblClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "contract_idContract");

            location.href = '/contract/edit/contractId/' + selectedId;
        });
    });

</script>
<style>
.dojoxGrid table {
    margin: 0;
}

table {
    width: 100%;
    border: none;
    border-collapse: collapse;
}

th {
    text-align: left;
    font-weight: bold;
}

tr:hover {
    background-color: transparent;
}

tr:first-child {
    background-color: transparent;
}

td, th {
    border: none;
    padding: 0px;
}
</style>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Contracts',
    'label'     => 'New Contract',
    'location'  => $this->url(array(
        'controller'    => 'contract',
        'action'        => 'add'
    ),'default', true)
)); ?>

<div dojotype="dojo.data.ItemFileReadStore" jsid="tableStore" data="contractStore"></div>

<table dojoType="dojox.grid.DataGrid" jsId="grid" store="tableStore" query="{ contract_idContract: '*' }" style="width: 100%; height: 65%; margin:auto;" autowidth="true" rowSelector="20px">
    <thead style="width: 100%;" >
        <tr>
            <th field="contract_idContract" width="50">Id</th>
            <th field="contract_client_name" width="200">Client</th>
            <th field="contract_dateStart">Start Date</th>
            <th field="contract_dateEnd">End Date</th>
            <th field="contract_desc" width="500">Description</th>
        </tr>
    </thead>
</table>

<?php
if ($this->contracts instanceof Zend_Paginator) {

    echo $this->paginationControl(
            $this->contracts,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}
?>


