<?php
	$this->title = "BBA Contracts";
	$this->headTitle($this->title);

    echo $this->contractSearchForm;
    /* @var $meter Power_Model_Meter */

?>

<script>
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "contract_idContract");

            location.href = '/contract/edit/contractId/' + selectedId;
        });
    });

</script>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Contracts',
    'label'     => 'New Contract',
    'location'  => $this->url(array(
        'controller'    => 'contract',
        'action'        => 'add'
    ),'default', true)
)); ?>

<div dojotype="dojox.data.QueryReadStore"
     jsid="tableStore"
     url="/contract/contract-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="grid"
       store="tableStore"
       query="<?php echo $this->search; ?>"
       style="width: 100%;height:500px;"
       autoWidth="false"
       autoHeight="false"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="contract_idContract" width="50">Id</th>
            <th field="client_name" width="200">Client</th>
            <th field="contract_reference" width="200">Reference</th>
            <th field="contract_dateStart" width="100">Start Date</th>
            <th field="contract_dateEnd" width="100">End Date</th>
            <th field="contract_desc" width="auto">Description</th>
        </tr>
    </thead>
</table>

<?php
if ($this->contracts instanceof Zend_Paginator) {

    echo $this->paginationControl(
            $this->contracts,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}
?>


