<?php
/* @var $form Power_Form_Tender_Save */
$form = $this->tenderSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';

if ($this->request['action'] == 'edit') {
    $form->getElement('tender_idSupplier')->setAttrib('readonly', true);
}
?>

<div data-dojo-type="dijit.Dialog"
     id="tenderForm"
     data-dojo-id="tenderForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Tender',
        execute: bba.Contract.processTenderForm">
    <div class="dijitDialogPaneContentArea">
        <div class="form_wrap">
            <div class="zend_form">
               <?php echo $form; ?>
				<div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>