<?php
	$this->title = "BBA Meter Usage Update";
	$this->headTitle($this->title);
?>
<div style="float:left;margin:5px;">
    <p><?php echo $this->meter->client_name; ?> </p>
    <p><?php echo $this->formatAddress(array(
        $this->escape($this->meter->clientAd_address1),
        $this->escape($this->meter->clientAd_address2),
        $this->escape($this->meter->clientAd_address3),
        $this->escape($this->meter->clientAd_postcode)
    )); ?></p>
</div>

<div style="float:left;margin:5px;margin-left:30px;">
    <p>Meter Type: <?php echo $this->escape($this->meter->type); ?></p>
    <p>Meter Number: <?php echo $this->escape($this->meter->numberMain); ?></p>
</div>

<div style="float:left;margin:5px;margin-left:30px;" class="form_wrap">
    <?php echo $this->usageSaveForm; ?>
</div>

<div class="clear"></div>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Usage',
    'label'     => 'Add Usage',
    'location'  => $this->url(array(
        'controller'    => 'usage',
        'action'        => 'add',
        'idMeter'    => $this->meter->id
    ),'default', true)
)); ?>

<div dojoType="dojox.data.QueryReadStore"
     jsid="usageStore"
     url="/usage/usage-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="usageGrid"
       store="usageStore"
       query="{ usage_idMeter: <?php echo $this->meter->id; ?> }"
       sortInfo="-3"
       style="width: 100%;"
       autoWidth="false"
       autoHeight="10"
       selectionMode="single"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
    <tr>
        <th field="usage_idUsage" width="50">Id</th>
        <th field="usage_dateBill" width="100">Bill Date</th>
        <th field="usage_dateReading" width="100">Reading Date</th>
        <th field="usage_type" width="100">Type</th>
        <th field="usage_usageDay" width="100">Day</th>
        <th field="usage_usageNight" width="100">Night</th>
        <th field="usage_usageOther" width="100">Other</th>
        <th field="" width="auto"></th>
    </tr>
    </thead>
</table>