<?php

require_once dirname(__FILE__) . '/../../../../../application/modules/power/controllers/UserController.php';

/**
 * Test class for Power_UserController.
 * Generated by PHPUnit on 2011-11-01 at 09:34:38.
 */
class Power_UserControllerTest extends ControllerTestCase
{
    /**
     * Displays user list.
     */
    public function testIndexAction() {
        $this->dispatch('/');
        $this->assertQuery('#auth');
        $this->tearDown();

        $this->doAuth();
        $this->dispatch('/user');
        $this->assertAction('index');
        $this->assertQuery('#userGrid');
        $this->tearDown();
    }

    /**
     * test user store turns list.
     */
    public function testUserStoreAction() {
        $this->dispatch('/');
        $this->assertQuery('#auth');
        $this->tearDown();
        
        $this->doAuth();
        $this->request->setHeader('X-Requested-With', 'XmlHttpRequest');
        $this->request->setMethod('POST')->setPost(array(
            'sort'  => 'client_name',
            'count' => 25,
            'start' => 0
        ));
        $this->dispatch('/user/user-store');
        $json = json_decode($this->getResponse()->getBody(), true);

        $this->assertArrayHasKey('identifier', $json);
        $this->assertArrayHasKey('items', $json);
        $this->assertArrayHasKey('numRows', $json);

        $this->tearDown();
    }

    /**
     * @todo Implement testAddAction().
     */
    public function testAddAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testEditAction().
     */
    public function testEditAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSaveAction().
     */
    public function testSaveAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
