<?php
	$this->title = "BBA Tender Update";
	$this->headTitle($this->title);
?>
<div class="ident alpha">
    <p><b>Client:</b> <?php echo $this->tender->client_name; ?></p>
    <p><b>Contract Ref:</b> <?php echo $this->tender->contract_reference; ?></p>
    <p><b>Type:</b> <?php echo $this->tender->contract_type; ?></p>
    <p><b>Status:</b> <?php echo $this->tender->contract_status; ?></p>
    <p><b>Start Date:</b> <?php echo $this->formatDate($this->tender->contract_dateStart); ?></p>
</div>

<div class="form_wrap ident">
    <?php echo $this->tenderSaveForm; ?>
</div>

<div class="clear"></div>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Tenders',
    'label'     => 'New Tender',
    'location'  => $this->url(array(
        'controller'    => 'tender',
        'action'        => 'add',
        'contractId'    => $this->tender->id
    ),'default', true)
)); ?>

<div dojoType="dojox.data.QueryReadStore"
     jsid="tenderStore"
     url="/tender/tender-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="tenderGrid"
       store="tenderStore"
       query="{ tender_idTender: <?php echo $this->tender->id; ?> }"
       sortInfo="1"
       style="margin:auto;"
       autoWidth="false"
       autoHeight="20"
       selectionMode="single"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
    <thead>
        <tr>
            <th field="tender_idTender" width="75">Id</th>
            <th field="tender_periodContract" width="100">Contract Period</th>
            <th field="tender_dateExpiresQuote" width="100">Quote Expires</th>
            <th field="tender_chargeStanding" width="100">Standing Charge</th>
            <th field="" width="auto"></th>
        </tr>
    </thead>
</table>
