<?php $form = $this->clientAddForm; ?>

<div data-dojo-type="dijit.Dialog"
     id="clientForm"
     data-dojo-id="clientForm"
     data-dojo-props="
        title:'New Client',
        execute: bba.Client.processClientForm">
    <div class="dijitDialogPaneContentArea">

        <div id="addClientWidget"
             data-dojo-type="dojox.widget.Wizard"
             data-dojo-props="doneButtonLabel: 'Save'">

            <div class="form_wrap wizard">
                <div data-dojo-type="dojox.widget.WizardPane"
                     class="zend_form client_edit">

                    <?php echo $form->client_name; ?>

                    <?php echo $form->client_docLoa; ?>

                    <?php echo $form->client_dateExpiryLoa; ?>

                    <?php echo $form->client_desc; ?>

                    <script type="dojo/method" data-dojo-event="onShow">
                        clientForm.attr('title', 'Client Information');
                    </script>
                </div>

                <div id="addClientWidgetPane1"
                    data-dojo-type="dojox.widget.WizardPane"
                     class="zend_form client_edit">

                    <?php echo $form->clientAd_address1; ?>

                    <?php echo $form->clientAd_address2; ?>

                    <?php echo $form->clientAd_address3; ?>

                    <?php echo $form->clientAd_postcode; ?>

                    <?php echo $form->clientAd_addressName; ?>

                    <script type="dojo/method" data-dojo-event="onShow">
                        clientForm.attr('title', 'Main (HQ) Address');
                        
                        dijit.byId('clientAd_addressName').attr('value', dijit.byId('client_name').attr('value'));                    
                    </script>
                </div>

                <div data-dojo-type="dojox.widget.WizardPane"
                     class="zend_form client_edit">

                    <?php echo $form->clientCo_type; ?>

                    <?php echo $form->clientCo_name; ?>

                    <?php echo $form->clientCo_position; ?>

                    <?php echo $form->clientCo_phone; ?>

                    <?php echo $form->clientCo_email; ?>

                    <input dojoType="dijit.form.TextBox"
                            type="hidden"
                            name="type"
                            id="type"
                            value="add" />

                    <script type="dojo/method" data-dojo-event="onShow">
                        clientForm.attr('title', 'Main Contact for BBA');
                        dijit.byId('clientAd_addressName').set('value', dijit.byId('client_name').get('value'));
                    </script>

                    <script type='dojo/method' data-dojo-event="doneFunction">
                        if (!clientForm.validate()) {
                            alert('Please recheck all form entries for mistakes.');
                            return false;
                        }
                        var vals = clientForm.get('value');

                        clientForm.execute(vals);
                        //clientGrid._refresh();
                    </script>
                </div>
            </div>
            <script type="dojo/method" data-dojo-event="cancelFunction">
                bba.closeDialog(dijit.byId('clientForm'));
            </script>
        </div>
    </div>
</div>