<?php
$form = $this->clientAddressSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="clientAdForm"
     data-dojo-id="clientAdForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Client Address',
        execute: bba.Client.processClientAdForm">
    <div class="dijitDialogPaneContentArea">
        <div class="form_wrap">
            <div class="zend_form">

                <?php echo $form; ?>

                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<div data-dojo-id="clientAdFormStandby"
     data-dojo-type="dojox.widget.Standby"
     data-dojo-props="target:'contractForm', color: '#efefef', image: 'images/loader_lg.gif'"></div>