<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">
        <div class="tabHeading">
            <div class="form_wrap zend_form client_edit ident alpha"
                 dojoType="dijit.form.Form"
                 id="edit-client-<?php echo $this->client->client_idClient; ?>">
                <h3>Client Details</h3>
                <div class="form_row">
                    <p class="label"><b>Client Name: </b></p>
                    <p><?php echo $this->client->client_name; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>LoA Expiry Date: </b></p>
                    <p><?php echo $this->formatDate($this->client->client_dateExpiryLoa); ?></p>
                </div>

                <button dojoType="dijit.form.Button"
                        type="submit"
                        name="edit-client-button-<?php echo $this->client->client_idClient; ?>"
                        value="submit">Edit Details</button>
            </div>

            <div class="ident">
                <h3>Main Address</h3>
                <div>
                    <p><?php
                        $mainContact = $this->clientHelper($this->client->id)
                            ->getParentRow('clientAd');

                        echo $this->formatAddress(array(
                            $mainContact->get('clientAd_addressName'),
                            $mainContact->get('clientAd_address1'),
                            $mainContact->get('clientAd_address2'),
                            $mainContact->get('clientAd_address3'),
                            $mainContact->get('clientAd_postcode')
                        ));
                    ?></p>
                </div>
            </div>

            <div class="ident">
                <h3>Main Contact</h3>
                <div>
                    <p><?php
                        $mainContact = $this->clientHelper($this->client->id)
                            ->getParentRow('clientCo');

                        echo $this->formatAddress(array(
                            $mainContact->get('clientCo_name'),
                            $mainContact->get('clientCo_position'),
                            $mainContact->get('clientCo_phone'),
                            $mainContact->get('clientCo_email')
                        ));
                    ?></p>
                </div>
            </div>
            <div class="clear"></div>

            <div class="tableHead">
                <?php if ($this->authInfo('role') == 'admin'): ?>
                <p class="tableHead-button">
                    <button dojoType="dijit.form.Button"
                            id="new-client-address-button-<?php echo $this->client->client_idClient; ?>"
                            type="button">New Address</button>
                </p>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div id="ClientTabs<?php echo $this->client->client_idClient; ?>"
         data-dojo-type="dijit.layout.TabContainer"
         data-dojo-props="region: 'center', tabStrip: 'true'"
         class="innerTabs">

        <div data-dojo-type="dijit.layout.ContentPane"
             data-dojo-props="region: 'center', title: 'Client Addresses'">

            <span dojoType="dojox.data.QueryReadStore"
                  jsid="clientAddressStore<?php echo $this->client->client_idClient; ?>"
                  url="/client-address/client-address-store"
                  requestMethod="post"></span>

            <table dojoType="bba.DataGrid"
                   jsId="addressGrid<?php echo $this->client->client_idClient; ?>"
                   store="clientAddressStore<?php echo $this->client->client_idClient; ?>"
                   query="{ clientAd_idClient: <?php echo $this->client->client_idClient; ?> }"
                   queryParent="clientAd_idClient"
                   sortInfo="2"
                   tabs="true"
                   tabTitleColumn="clientAd_addressName">
                <thead>
                    <tr>
                        <th field="clientAd_idAddress" width="50">Id</th>
                        <th field="clientAd_addressName" width="250">Address Name</th>
                        <th field="clientAd_address1" width="300">Address 1</th>
                        <th field="clientAd_address2" width="200">Address 2</th>
                        <th field="clientAd_address3" width="100">Address 3</th>
                        <th field="clientAd_postcode" width="100">Postcode</th>
                        <th field="" width="auto"></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
