<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">
            <table class="info_wrap">
                <caption>Client Address Details</caption>
                <tr>
                    <th>Address Name:</th>
                    <td><?php echo $this->clientAd->clientAd_addressName; ?></td>
                </tr>
                <tr>
                    <th>Address 1:</th>
                    <td><?php echo $this->clientAd->clientAd_address1; ?></td>
                </tr>
                <tr>
                    <th>Address 2:</th>
                    <td><?php echo $this->clientAd->clientAd_address2; ?></td>
                </tr>
                <tr>
                    <th>Address 3:</th>
                    <th><?php echo $this->clientAd->clientAd_address3; ?></th>
                </tr>
                <tr>
                    <th>Postcode:</th>
                    <td><?php echo $this->clientAd->clientAd_postcode; ?></td>
                </tr>

                <?php if ($this->isAllowed('User')): ?>
                <tr>
                    <td class="footer" colspan="2">
                        <div dojoType="dijit.form.Form"
                             id="edit-clientAd-<?php echo $this->clientAd->clientAd_idAddress; ?>">
                            <button dojoType="dijit.form.Button"
                                    type="submit"
                                    name="edit-clientAd-button-<?php echo $this->clientAd->clientAd_idAddress; ?>"
                                    value="submit">Edit Details</button>
                        </div>
                    </td>
                </tr>
                <?php endif; ?>
            </table>
            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="clientAddressEditTabs-BorderContainter">

        <div id="ClientAdTabs<?php echo $this->clientAd->clientAd_idAddress; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Contacts'">

                <span dojoType="dojox.data.QueryReadStore"
                      jsid="clientContactStore<?php echo $this->clientAd->clientAd_idClient; ?>"
                      url="/client/data-store/type/contact"
                      requestMethod="post"></span>

                <table dojoType="bba.DataGrid"
                       jsId="contactGrid<?php echo $this->clientAd->clientAd_idClient; ?>"
                       store="clientContactStore<?php echo $this->clientAd->clientAd_idClient; ?>"
                       structure="bba.Client.gridLayouts.clientContact"
                       query="{ clientCo_idClient: <?php echo $this->clientAd->clientAd_idClient; ?>,
                       clientCo_idAddress: <?php echo $this->clientAd->clientAd_idAddress; ?>}"
                       queryParent="clientCo_idClient"
                       sortInfo="2"
                       newButtonId="<?php echo $this->clientAd->clientAd_idAddress; ?>"
                       dialog="true">
                </table>

            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <div class="tableHead">
                <p class="tableHead-button">
                    <button dojoType="dijit.form.Button"
                            id="new-client-contact-button-<?php echo $this->clientAd->clientAd_idAddress; ?>"
                            type="button">New Contact</button>
                </p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
