<?php $form = $this->clientSaveForm; ?>

<div class="form_wrap">
    <div class="zend_form">

        <?php echo $form->client_name; ?>

        <?php echo $form->client_dateExpiryLoa; ?>

        <?php echo $form->client_idAddress; ?>

        <?php echo $form->client_idClientContact; ?>

        <input dojoType="dijit.form.TextBox"
               type="hidden"
               name="client_idClient"
               id="client_idClient"
               required="true"
               value="<?php echo $form->client_idClient->getValue(); ?>" />

        <button dojoType="dijit.form.Button"
                type="submit"
                id="clientFormSubmitButton"
                name="submit"
                value="Save">Save</button>

        <button dojoType="dijit.form.Button"
                type="button"
                id="clientFormCancelButton"
                name="cancel"
                value="Cancel">Cancel</button>
    </div>
</div>