<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top', splitter: 'true'">
        <div class="tabHeading">

            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Client Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->client->client_idClient; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('User')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Client.editClientButtonClick({
                                    client_idClient : <?php echo $this->client->client_idClient; ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Client Name:</th>
                    <td><?php echo $this->client->client_name; ?></td>
                </tr>
                <tr>
                    <th>Company Number:</th>
                    <td><?php echo $this->client->client_numberCompany; ?></td>
                </tr>
                 <tr>
                    <th>Company VAT Number:</th>
                    <td><?php echo $this->client->client_numberVAT; ?></td>
                </tr>
                <tr>
                    <th>LoA Expiry Date:</th>
                    <td><?php echo $this->formatDate($this->client->client_dateExpiryLoa); ?></td>
                </tr>
                <tr>
                    <th>LoA Doc:</th>
                    <td>
                        <?php echo $this->DocLoa($this->client)->getCurrentFile(); ?>
                        <?php if ($files = $this->DocLoa($this->client)->getFileList()): ?><br />
                        <a href="#" onClick="dijit.byId('client<?php echo $this->client->client_idClient; ?>FileList').show(); return false;">
                            Show All ...
                        </a>
                        <?php
                            echo $this->partial('filelist.phtml', array(
                                'row' => $this->client,
                                'files' => $files,
                                'id' => $this->client->client_idClient,
                                'controller' => 'client',
                                'docClass'   => 'DocLoa'
                            ));
                        ?>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>Description</caption>
                <tr>
                    <td class="description"><?php echo $this->client->getShortDesc(); ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>
                	<?php echo ($this->client->client_idAddress == $this->client->client_idRegAddress) ?
                		'Main & Registered Address' : 'Main Address'?>
                </caption>
                <tr>
                    <td><?php
                        $mainContact = $this->client->getClientAddress();

                        echo $this->formatAddress(array(
                            $mainContact->clientAd_addressName,
                            $mainContact->clientAd_address1,
                            $mainContact->clientAd_address2,
                            $mainContact->clientAd_address3,
                            $mainContact->clientAd_postcode
                        ));
                    ?></td>
                </tr>
            </table>
            
            <?php if ($this->client->client_idAddress != $this->client->client_idRegAddress): ?>
            <table class="info_wrap ident">
                <caption>
                	Main & Registered Address
                </caption>
                <tr>
                    <td><?php
                        $regContact = $this->client->getClientRegAddress();

                        echo $this->formatAddress(array(
                            $regContact->clientAd_addressName,
                            $regContact->clientAd_address1,
                            $regContact->clientAd_address2,
                            $regContact->clientAd_address3,
                            $regContact->clientAd_postcode
                        ));
                    ?></td>
                </tr>
            </table>
            <?php endif; ?>

            <table class="info_wrap ident">
                <caption>Main Liaison</caption>
                <tr>
                    <td>
                        <?php $mainContact = $this->client->getClientPersonnel(); ?>
                        <?php if (isset($mainContact->clientPers_idClientPersonnel)): ?>
                            <?php echo $this->formatAddress(array(
                                $mainContact->clientPers_name,
                                $mainContact->clientPers_position,
                                $mainContact->clientPers_phone,
                                $mainContact->getMailto()
                            )); ?>
                        <?php else: ?>
                        <p>No Contact Available</p>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'center'"
         class="clientEditTabs-BorderContainter">

        <!-- start client address list -->
        <div id="ClientTabs<?php echo $this->client->client_idClient; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Addresses'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'client/data-store/type/address', requestMethod: 'post'"
                      data-dojo-id="clientAdStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientAdGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientAdGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientAdStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Client.gridLayouts.clientAddress,
                        query: { clientAd_idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Client.clientAdGridRowClick(this, {
                            clientAd_idClient : <?php echo $this->client->client_idClient; ?>
                        });
                    </script>
                </table>
            </div>
            <!-- end client address list -->

            <!-- start client contacts list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Personnel'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'client/data-store/type/personnel', requestMethod: 'post'"
                      data-dojo-id="clientPersStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientPersGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientPersGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientPersStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Client.gridLayouts.clientPersonnel,
                        query: { clientPers_idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Client.clientPersGridRowClick(this, {
                                clientPers_idClient : <?php echo $this->client->client_idClient ?>
                            });
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client contact list -->

            <!-- start client sites list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Sites'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'site/data-store/type/site', requestMethod: 'post'"
                      data-dojo-id="clientSiteStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientSiteGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientSiteGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientSiteStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Site.gridLayouts.site,
                        query: { idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Site.siteGridRowClick(this);
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client sites list -->

            <!-- start client meters list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Meters'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'meter/data-store/type/meter', requestMethod: 'post'"
                      data-dojo-id="clientMeterStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientMeterGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientMeterGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientMeterStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Meter.gridLayouts.meter,
                        query: { idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Meter.meterGridRowClick(this);
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client meters list -->

            <!-- start client contract list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Contracts'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'contract/data-store/type/contract', requestMethod: 'post'"
                      data-dojo-id="clientContractStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientContractGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientContractGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientContractStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Contract.gridLayouts.contract,
                        query: { contract_idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Contract.contractGridRowClick(this);
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client contract list -->
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <div class="tableHead">
                <p class="tableHead-button">
                    <button data-dojo-type="dijit.form.Button">
                        New Contract
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Contract.newContractButtonClick({
                                contract_idClient : <?php echo $this->client->client_idClient; ?>
                            });
                        </script>
                    </button>
                    <button data-dojo-type="dijit.form.Button">
                        New Address
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Client.newClientAdButtonClick({
                                clientAd_idClient : <?php echo $this->client->client_idClient; ?>
                            });
                        </script>
                    </button>
                    <button data-dojo-type="dijit.form.Button" data-dojo-props="type:'button'">
                        New Client Personnel
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Client.newClientPersButtonClick({
                                clientPers_idClient : <?php echo $this->client->client_idClient; ?>
                            });
                        </script>
                    </button>
                </p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
