<?php
	$this->title = "BBA Client Update";
	$this->headTitle($this->title);

    echo $this->clientSaveForm;
	
	echo '<div class="clear"> &nbsp; </div><p style="margin:0px">&nbsp;</p>';
	
    echo $this->partial('_client-addresses.phtml', array(
        'idClient'  => $this->client,
        'addresses'  => $this->clientAddresses($this->client)
    ));

    echo $this->partial('_client-contacts.phtml', array(
        'idClient'  => $this->client,
        'contacts'  => $this->clientContacts($this->client)
    ));
?>
