<?php
	$this->title = "BBA Client Update";
	$this->headTitle($this->title);

    echo $this->clientSaveForm;
    $addresses = $this->clientAddresses($this->client->getId());
?>

<h2>Client Addresses</h2>
<p>
    <a href="<?php echo $this->url(array(
        'controller'    => 'client',
        'action'        => 'addAddress'
        ), 'default', true);?>" class="button">Add New Address</a>
</p>

<?php if ($addresses): ?>
    <?php foreach($addresses as $address): ?>

    <?php endforeach; ?>
<?php else: ?>
<h3>No Client Addresses</h3>
<?php endif; ?>

<h2>Client Contacts</h2>

<p>
    <a href="<?php echo $this->url(array(
        'controller'    => 'client',
        'action'        => 'addContact'
        ), 'default', true);?>" class="button">Add New Contact</a>
</p>