<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">
            <div class="form_wrap zend_form ident"
                 dojoType="dijit.form.Form"
                 id="edit-clientAd-<?php echo $this->clientAd->clientAd_idAddress; ?>">
                <h3>Client Address Details</h3>
                <div class="form_row">
                    <p class="label"><b>Address Name: </b></p>
                    <p>&nbsp;<?php echo $this->clientAd->clientAd_addressName; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Address 1: </b></p>
                    <p>&nbsp;<?php echo $this->clientAd->clientAd_address1; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Address 2: </b></p>
                    <p>&nbsp;<?php echo $this->clientAd->clientAd_address2; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Address 3: </b></p>
                    <p>&nbsp;<?php echo $this->clientAd->clientAd_address3; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Postcode: </b></p>
                    <p>&nbsp;<?php echo $this->clientAd->clientAd_postcode; ?></p>
                </div>

                <?php if ($this->isAllowed('User')): ?>
                <button dojoType="dijit.form.Button"
                        type="submit"
                        name="edit-clientAd-button-<?php echo $this->clientAd->clientAd_idAddress; ?>"
                        value="submit">Edit Details</button>
                <?php endif; ?>
            </div>
            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="clientAddressEditTabs-BorderContainter">

        <div id="ClientAdTabs<?php echo $this->clientAd->clientAd_idAddress; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Contacts'">

                <span dojoType="dojox.data.QueryReadStore"
                      jsid="clientContactStore<?php echo $this->clientAd->clientAd_idClient; ?>"
                      url="/client/data-store/type/contact"
                      requestMethod="post"></span>

                <table dojoType="bba.DataGrid"
                       jsId="contactGrid<?php echo $this->clientAd->clientAd_idClient; ?>"
                       store="clientContactStore<?php echo $this->clientAd->clientAd_idClient; ?>"
                       structure="bba.Client.gridLayouts.clientAddress"
                       query="{ clientCo_idClient: <?php echo $this->clientAd->clientAd_idClient; ?>,
                       clientCo_idAddress: <?php echo $this->clientAd->clientAd_idAddress; ?>}"
                       queryParent="clientCo_idClient"
                       sortInfo="2"
                       newButtonId="<?php echo $this->clientAd->clientAd_idAddress; ?>"
                       dialog="true">
                </table>

            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <div class="tableHead">
                <p class="tableHead-button">
                    <button dojoType="dijit.form.Button"
                            id="new-client-contact-button-<?php echo $this->clientAd->clientAd_idAddress; ?>"
                            type="button">New Contact</button>
                </p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
