<div data-dojo-type="dijit.Dialog"
     id="clientForm"
     data-dojo-id="clientForm"
     data-dojo-props="
        title:'Edit Client',
        execute: bba.Client.processClientForm">
    <div class="dijitDialogPaneContentArea">
        <div class="form_wrap">
            <div class="zend_form">
            	<form method="post" action="<?php echo $this->url(array(
                    'controller' => 'client',
                    'action' => 'save-client',
                    'module' => 'power'
                ), 'default'); ?>" enctype="multipart/form-data">
                
                	<?php echo $this->clientForm; ?>
                	
                </form>
                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<div data-dojo-id="clientFormStandby"
     data-dojo-type="dojox.widget.Standby"
     data-dojo-props="target:'clientForm', color: '#efefef', image: 'images/loader_lg.gif'"></div>