<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top', splitter: 'true'">
        <div class="tabHeading">
            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Client Address Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->clientAd->clientAd_idAddress; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('ClientAd', 'edit')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Client.editClientAdButtonClick({
                                    clientAd_idAddress : <?php echo $this->clientAd->clientAd_idAddress ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Address Name:</th>
                    <td><?php echo $this->clientAd->clientAd_addressName; ?></td>
                </tr>
                <tr>
                    <th>Address 1:</th>
                    <td><?php echo $this->clientAd->clientAd_address1; ?></td>
                </tr>
                <tr>
                    <th>Address 2:</th>
                    <td><?php echo $this->clientAd->clientAd_address2; ?></td>
                </tr>
                <tr>
                    <th>Town/City:</th>
                    <td><?php echo $this->clientAd->clientAd_address3; ?></td>
                </tr>
                <tr>
                    <th>Postcode:</th>
                    <td><?php echo $this->clientAd->clientAd_postcode; ?></td>
                </tr>
            </table>
            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'center'"
         class="clientAddressEditTabs-BorderContainter">

        <div id="ClientAdTabs<?php echo $this->clientAd->clientAd_idAddress; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">
			<?php if ($this->isAllowed('ClientPers', 'view')): ?>
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Personnel'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'client/data-store/type/personnel', requestMethod: 'post'"
                      data-dojo-id="clientAdPersStore<?php echo $this->clientAd->clientAd_idAddress; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientAdPersGrid<?php echo $this->clientAd->clientAd_idAddress; ?>"
                       id="clientAdPersGrid<?php echo $this->clientAd->clientAd_idAddress; ?>"
                       data-dojo-props="
                        store: clientAdPersStore<?php echo $this->clientAd->clientAd_idAddress; ?>,
                        structure: bba.Client.gridLayouts.clientPersonnel,
                        query: {
                            clientPers_idClient: <?php echo $this->clientAd->clientAd_idClient; ?>,
                            clientPers_idAddress: <?php echo $this->clientAd->clientAd_idAddress; ?>
                        },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                    <?php if ($this->isAllowed('ClientPers', 'edit')): ?>
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Client.clientPersGridRowClick(this, {
                            clientPers_idClient : <?php echo $this->clientAd->clientAd_idClient ?>,
                            clientPers_idAddress : <?php echo $this->clientAd->clientAd_idAddress ?>
                        });
                    </script>
                    <?php endif; ?>
                </table>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('ClientPers', 'add')): ?>
            <div class="tableHead">
                <p class="tableHead-button">
                     <button data-dojo-type="dijit.form.Button">
                         New Client Personnel
                         <script type="dojo/method" data-dojo-event="onClick">
                            bba.Client.newClientPersButtonClick({
                                clientPers_idClient : <?php echo $this->clientAd->clientAd_idClient ?>,
                                clientPers_idAddress : <?php echo $this->clientAd->clientAd_idAddress ?>
                            });
                        </script>
                     </button>
                </p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
