<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <table class="info_wrap">
                <caption>Client Details</caption>
                <tr>
                    <th>Client Name:</th>
                    <td><?php echo $this->client->client_name; ?></td>
                </tr>
                <tr>
                    <th>LoA Expiry Date:</th>
                    <td><?php echo $this->formatDate($this->client->client_dateExpiryLoa); ?></td>
                </tr>
                <?php if ($this->isAllowed('User')): ?>
                <tr>
                    <td class="footer" colspan="2">
                        <button data-dojo-type="dijit.form.Button">
                            Edit Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Client.editClientButtonClick({
                                    client_idClient : <?php echo $this->client->client_idClient; ?>
                                });
                            </script>
                        </button>
                    </td>
                </tr>
                <?php endif; ?>
            </table>

            <table class="info_wrap ident">
                <caption>Description</caption>
                <tr>
                    <td class="description"><?php echo $this->client->client_desc; ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>Main Address</caption>
                <tr>
                    <td><?php
                        $mainContact = $this->clientHelper($this->client->client_idClient)
                            ->getParentRow('clientAd');

                        echo $this->formatAddress(array(
                            $mainContact->get('clientAd_addressName'),
                            $mainContact->get('clientAd_address1'),
                            $mainContact->get('clientAd_address2'),
                            $mainContact->get('clientAd_address3'),
                            $mainContact->get('clientAd_postcode')
                        ));
                    ?></td>
                </tr>
            </table>

            <table class="info_wrap ident">
                <caption>Main Contact</caption>
                <tr>
                    <td>
                        <?php $mainContact = $this->clientHelper($this->client->client_idClient)
                                ->getParentRow('clientCo'); ?>
                        <?php if ($mainContact->get('clientCo_idClientContact')): ?>
                            <?php echo $this->formatAddress(array(
                                $mainContact->get('clientCo_name'),
                                $mainContact->get('clientCo_position'),
                                $mainContact->get('clientCo_phone'),
                                $mainContact->get('clientCo_email')
                            )); ?>
                        <?php else: ?>
                        <p>No Contact Available</p>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="clientEditTabs-BorderContainter">

        <!-- start client address list -->
        <div id="ClientTabs<?php echo $this->client->client_idClient; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Addresses'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: '/client/data-store/type/address', requestMethod: 'post'"
                      data-dojo-id="clientAdStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientAdGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientAdGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientAdStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Client.gridLayouts.clientAddress,
                        query: { clientAd_idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Client.clientAdGridRowClick(this, {
                            clientAd_idClient : <?php echo $this->client->client_idClient; ?>
                        });
                    </script>
                </table>
            </div>
            <!-- end client address list -->

            <!-- start client contacts list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Contacts'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: '/client/data-store/type/contact', requestMethod: 'post'"
                      data-dojo-id="clientCoStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientCoGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientCoGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientCoStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Client.gridLayouts.clientContact,
                        query: { clientCo_idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Client.clientCoGridRowClick(this, {
                                clientCo_idClient : <?php echo $this->client->client_idClient ?>
                            });
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client contact list -->

            <!-- start client sites list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Sites'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: '/site/data-store/type/site', requestMethod: 'post'"
                      data-dojo-id="clientSiteStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientSiteGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientSiteGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientSiteStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Site.gridLayouts.site,
                        query: { idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Site.siteGridRowClick(this);
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client sites list -->

            <!-- start client meters list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Client Meters'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: '/meter/data-store/type/meter', requestMethod: 'post'"
                      data-dojo-id="clientMeterStore<?php echo $this->client->client_idClient; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="clientMeterGrid<?php echo $this->client->client_idClient; ?>"
                       id="clientMeterGrid<?php echo $this->client->client_idClient; ?>"
                       data-dojo-props="
                        store: clientMeterStore<?php echo $this->client->client_idClient; ?>,
                        structure: bba.Meter.gridLayouts.meter,
                        query: { idClient: <?php echo $this->client->client_idClient; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Meter.meterGridRowClick(this);
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end client meters list -->

            <!-- start client contract list -->
            <!-- end client contract list -->
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <div class="tableHead">
                <p class="tableHead-button">
                    <button data-dojo-type="dijit.form.Button">
                        New Contract
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Contract.newContractButtonClick({
                                contract_idClient : <?php echo $this->client->client_idClient; ?>
                            });
                        </script>
                    </button>
                    <button data-dojo-type="dijit.form.Button">
                        New Address
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Client.newClientAdButtonClick({
                                clientAd_idClient : <?php echo $this->client->client_idClient; ?>
                            });
                        </script>
                    </button>
                    <button data-dojo-type="dijit.form.Button" data-dojo-props="type:'button'">
                        New Contact
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Client.newClientCoButtonClick({
                                clientCo_idClient : <?php echo $this->client->client_idClient; ?>
                            });
                        </script>
                    </button>
                </p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
