<?php
	$this->title = "BBA Clients";
	$this->headTitle($this->title);

    echo $this->clientSearchForm;
    /* @var $client Power_Model_Client */
?>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Clients',
    'label'     => 'New Client',
    'location'  => $this->url(array(
        'controller'    => 'client',
        'action'        => 'add'
    ), 'default', true)
)); ?>

<script>
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "client_idClient");

            var formNode = dojo.create("form", {
                action:"/client/edit",
                method:"post"
            }, dojo.body());

            dojo.create("input", {
                type:"hidden",
                name:"clientId",
                value:selectedId
            },formNode);

            formNode.submit();
        });
    });

</script>

<div dojotype="dojox.data.QueryReadStore"
     jsid="tableStore"
     url="/client/client-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="grid"
       store="tableStore"
       query="<?php echo $this->search; ?>"
       style="margin:auto;"
       autoWidth="true"
       autoHeight="20"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="client_idClient" width="75">Id</th>
            <th field="client_name" width="300">Client</th>
            <th field="client_desc" width="200">Description</th>
            <th field="clientAd_address1" width="300">Address 1</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
			<th field=" " width="auto"> </th>
        </tr>
    </thead>
</table>

<?php
/*
if ($this->clients instanceof Zend_Paginator) {
    echo $this->paginationControl(
            $this->clients,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}*/
?>