<?php $this->dojo()->requireModule('bba/Client', true); ?>
<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">

        <div class="tabHeading">
            <?php
                $this->title = "BBA Clients";
                $this->headTitle($this->title);

                echo $this->clientSearchForm;
            ?>

            <div class="tableHead">
                <h2 class="tableHead-heading">Clients:</h2>
                <?php if ($this->isAllowed('User')): ?>
                <p class="tableHead-button">
                    <button data-dojo-type="dijit.form.Button">
                        New Client
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.Client.newClientButtonClick();
                        </script>
                    </button>
                </p>
                <?php endif; ?>
            </div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <span data-dojo-type="dojox.data.QueryReadStore"
              data-dojo-props="url: '<?php echo $this->baseUrl('client/data-store/type/client'); ?>', requestMethod: 'post'"
              data-dojo-id="clientStore"></span>

        <table data-dojo-type="dojox.grid.DataGrid"
               data-dojo-id="clientGrid"
               id="clientGrid"
               data-dojo-props='
                store: clientStore,
                structure: bba.Client.gridLayouts.client,
                query: <?php echo $this->search; ?>,
                sortInfo: "2",
                noDataMessage : bba.gridMessage'>
            <script type="dojo/method" data-dojo-event="onRowClick">
                bba.Client.clientGridRowClick(this);
            </script>
        </table>
    </div>
</div>