<?php
	$this->title = "BBA Clients";
	$this->headTitle($this->title);

    echo $this->clientSearchForm;
    /* @var $client Power_Model_Client */
?>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Clients',
    'label'     => 'New Client',
    'location'  => $this->url(array(
        'controller'    => 'client',
        'action'        => 'add'
    ), 'default', true)
)); ?>

<script>
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "client_idClient");

            location.href = '/client/edit/clientId/' + selectedId;
        });
    });

</script>

<div dojotype="dojox.data.QueryReadStore"
     jsid="tableStore"
     url="/client/client-store<?php echo $this->search; ?>"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="grid"
       store="tableStore"
       query="{}"
       style="width: 100%; height: 500px;"
       autoWidth="false"
       autoHeight="false"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="client_idClient" width="75">Id</th>
            <th field="client_name" width="auto">Client</th>
            <th field="client_desc" width="auto">Description</th>
            <th field="clientAd_address1" width="300">Address 1</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
        </tr>
    </thead>
</table>

<?php
/*
if ($this->clients instanceof Zend_Paginator) {
    echo $this->paginationControl(
            $this->clients,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}*/
?>