<?php
/* @var $form ZendSF_Form_Abstract */
$form = $this->clientPersonnelSaveForm;
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="clientPersForm"
     data-dojo-id="clientPersForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Client Personnel Details',
        execute: bba.Client.processClientPersForm">
    <div class="dijitDialogPaneContentArea">
        <div class="form_wrap">
            <div class="zend_form">

                <?php echo $form; ?>

                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>