<?php
    $this->title = "BBA Add Site";
    $this->headTitle($this->title);
?>

<div class="form_wrap">
    <?php echo $this->siteAddForm; ?>
</div>

<script>
    dojo.declare("bba.store", null, {
        constructor: function(/* Object */args){
            dojo.safeMixin(this, args);
        }
    });

    dojo.addOnLoad(function(){
        dojo.connect(dijit.byId("site_idClient"), "onChange", function(val){
            if (dijit.byId("site_idAddress").get('disabled') == true) {
                dijit.byId("site_idAddress").set('disabled', false);
            }
            dijit.byId('site_idAddress').set('value', '');
            dijit.byId('site_idAddressBill').set('value', '');

            bba.clientId = val;
            bba.addressStore = new dojo.data.ItemFileReadStore({
                url:'/site/autocomplete/param/address/addressId/' + bba.store.clientId
            });
            dijit.byId("site_idAddress").store = bba.store.addressStore;
        });

        dojo.connect(dijit.byId("site_idAddress"), "onChange", function(){
            dijit.byId("site_idAddressBill").set('disabled', false);
            dijit.byId("site_idAddressBill").store = bba.store.addressStore;
        });
    });
</script>
