<?php $form = $this->{$this->formName}; ?>

<div class="form_wrap">
    <div class="zend_form">

        <?php echo $form->site_idClient; ?>

        <?php echo $form->site_idAddress; ?>

        <?php echo $form->site_idAddressBill; ?>

        <?php echo $form->site_idClientContact; ?>

        <input dojoType="dijit.form.TextBox"
               type="hidden"
               name="userId"
               id="userId"
               required="true"
               value="<?php echo $form->userId->getValue(); ?>" />

        <input dojoType="dijit.form.TextBox"
               type="hidden"
               name="site_idSite"
               id="site_idSite"
               required="true"
               value="<?php echo $form->site_idSite->getValue(); ?>" />

        <button dojoType="dijit.form.Button"
                type="submit"
                id="siteFormSubmitButton"
                name="submit"
                value="Save">Save</button>

        <button dojoType="dijit.form.Button"
                type="button"
                id="siteFormCancelButton"
                name="cancel"
                value="Cancel">Cancel</button>
    </div>
</div>

<script>
    dojo.declare("bbastore", null, {
        constructor: function(/* Object */args){
            dojo.safeMixin(this, args);
        }
    });

    dojo.addOnLoad(function(){
        dojo.connect(dijit.byId("site_idClient"), "onChange", function(val){
            if (dijit.byId("site_idAddress").get('disabled') == true) {
                dijit.byId("site_idAddress").set('disabled', false);
            }
            dijit.byId('site_idAddress').set('value', '');
            dijit.byId('site_idAddressBill').set('value', '');

            bbastore.clientId = val;
            bbastore.addressStore = new dojo.data.ItemFileReadStore({
                url:'/site/autocomplete/param/address/addressId/' + bbastore.clientId
            });
            dijit.byId("site_idAddress").store = bbastore.addressStore;
        });

        dojo.connect(dijit.byId("site_idAddress"), "onChange", function(val){
            dijit.byId("site_idAddressBill").set('disabled', false);
            dijit.byId("site_idAddressBill").store = bbastore.addressStore;
        });
    });
</script>