<?php
    $this->title = "BBA Site Update";
    $this->headTitle($this->title);

    echo $this->siteEditForm;
?>
<div class="tableHead">
	<h2 class="tableHead-heading">Meters</h2>
	<p class="tableHead-button">
		<a href="<?php echo $this->url(array(
			'controller'    => 'meter',
			'action'        => 'add',
			'siteId'      => $this->site
        ), 'default', true);?>" class="button">New Meter</a>
	</p>
</div>

<table>
    <tr>
        <th>Type <span class="id">(id)</span></th>
        <th>Number Serial</th>
        <th>Number Main</th>
        <th>&nbsp;</th>
	</tr>
<?php
	if ($this->meters):
		foreach($this->meters as $meter):
?>
    <tr>
        <td><?php echo $meter->type; ?>&nbsp;
            <span class="id">(<?php echo $this->escape($meter->id); ?>)</span></td>
        <td><?php echo $meter->numberSerial; ?></td>
        <td><?php echo $meter->numberMain; ?></td>
        <td class="action">
            <a href="<?php echo $this->url(array(
                'controller'    => 'usage',
                'action'        => 'index',
                'meterId'       => $meter->id
            ), 'default', true);?>" class="button">Usage</a>

            <a href="<?php echo $this->url(array(
                'controller'    => 'meter',
                'action'        => 'edit',
                'meterId'       => $meter->id
            ),'default', true);?>" class="button">Edit</a>
<!--
            <a href="<?php echo $this->url(array(
                'controller'    => 'meter',
                'action'        => 'delete',
                'meterId'       => $meter->id
            ), 'default', true);?>" class="button">Delete</a>
-->
        </td>
    </tr>
<?php endforeach;
else: ?>
    <tr><td>This Site has no meters yet.</td>
        <td></td><td></td><td></td><td></td><td></td>
    </tr>
<?php endif; ?>
</table>
<script>
    dojo.declare("bba", null, {
        constructor: function(/* Object */args){
            dojo.safeMixin(this, args);
        }
    });

    dojo.addOnLoad(function(){
        dojo.connect(dijit.byId("site_idClient"), "onChange", function(val){
            if (dijit.byId("site_idAddress").get('disabled') == true) {
                dijit.byId("site_idAddress").set('disabled', false);
            }
            dijit.byId('site_idAddress').set('value', '');
            dijit.byId('site_idAddressBill').set('value', '');

            bba.clientId = val;
            bba.addressStore = new dojo.data.ItemFileReadStore({
                url:'/site/autocomplete/param/address/addressId/' + bba.clientId
            });
            dijit.byId("site_idAddress").store = bba.addressStore;
        });

        dojo.connect(dijit.byId("site_idAddress"), "onChange", function(val){
            dijit.byId("site_idAddressBill").set('disabled', false);
            dijit.byId("site_idAddressBill").store = bba.addressStore;
        });
    });
</script>