<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">
        <div class="tabHeading">
            <div class="ident alpha">
                <p><?php echo $this->escape($this->site->client_name); ?> </p>
                <p><?php echo $this->escape($this->site->clientAd_addressName); ?></p>
                <p><?php echo $this->formatAddress(array(
                    $this->escape($this->site->clientAd_address1),
                    $this->escape($this->site->clientAd_address2),
                    $this->escape($this->site->clientAd_address3),
                    $this->escape($this->site->clientAd_postcode)
                )); ?></p>
            </div>

            <div class="form_wrap zend_form ident"
                 dojoType="dijit.form.Form"
                 id="edit-site-<?php echo $this->site->id; ?>">
                <h2>Site Details</h2>
                <div class="form_row">
                    <p class="label"><b>Client:</b></p>
                    <p>&nbsp;<?php echo $this->site->client_name; ?></p>
                </div>
                <div class="form_row">
                    <p class="label"><b>Address:</b></p>
                    <p>&nbsp;</p>
                </div>
                 <div class="form_row">
                    <p class="label"><b>Billing Address:</b></p>
                    <p>&nbsp;</p>
                </div>
                 <div class="form_row">
                    <p class="label"><b>Client Contact:</b></p>
                    <p>&nbsp;</p>
                </div>

                <button dojoType="dijit.form.Button"
                    type="submit"
                    name="edit-site-button-<?php echo $this->site->id; ?>"
                    value="submit">Edit Details</button>
            </div>

            <div class="clear"></div>

            <div class="tableHead">
                <?php if ($this->authInfo('role') == 'admin'): ?>
                <p class="tableHead-button">
                    <button dojoType="dijit.form.Button"
                            id="new-meter-button-<?php echo $this->site->id; ?>"
                            type="button">New Meter</button>
                </p>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div id="SiteTabs<?php echo $this->site->id; ?>"
         data-dojo-type="dijit.layout.TabContainer"
         data-dojo-props="region: 'center', tabStrip: 'true'"
         class="innerTabs">

        <div data-dojo-type="dijit.layout.ContentPane"
             data-dojo-props="region: 'center', title: 'Meters'">

            <span dojoType="dojox.data.QueryReadStore"
                 jsid="meterStore<?php echo $this->site->id; ?>"
                 url="/meter/site-meter-store"
                 requestMethod="post"></span>

            <table dojoType="dojox.grid.DataGrid"
                   jsId="meterGrid<?php echo $this->site->id; ?>"
                   store="meterStore<?php echo $this->site->id; ?>"
                   query="{ meter_idSite: <?php echo $this->site->id; ?> }"
                   queryParent="meter_idSite"
                   sortInfo="-3"
                   dialog="true"
                   dialogName="Edit Meter">
                <thead>
                    <tr>
                        <th field="meter_idMeter" width="75">Id</th>
                        <th field="meter_type" width="100">Type</th>
                        <th field="meter_numberSerial" width="200">Number Serial</th>
                        <th field="meter_numberMain" width="200">Number Main</th>
                        <th field="" width="auto"></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

