<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top', splitter: 'true'">
        <div class="tabHeading">

            <?php $mainContact = $this->site->getSiteAddress(); ?>

            <table class="info_wrap">
                <tr>
                    <td colspan="2">
                        <span class="caption">Site Details&nbsp;
                            <span class="id_number">
                                (<?php echo $this->site->site_idSite; ?>)
                            </span>
                        </span>
                        <?php if ($this->isAllowed('User')): ?>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Site Details
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Site.editSiteButtonClick({
                                    site_idSite : <?php echo $this->site->site_idSite; ?>
                                });
                            </script>
                        </button>
                        <button data-dojo-type="dijit.form.Button">
                            Edit Site Address
                            <script type="dojo/method" data-dojo-event="onClick">
                                bba.Client.editClientAdButtonClick({
                                    clientAd_idAddress : <?php echo $this->site->site_idAddress ?>,
									site_idSite : <?php echo $this->site->site_idSite; ?>
                                });
                            </script>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Client:</th>
                    <td><?php echo $this->site->getClient('client_name'); ?></td>
                </tr>
                <?php if($mainContact->clientAd_addressName): ?>
                <tr>
                    <th>Address Name:</th>
                    <td><?php echo $mainContact->clientAd_addressName; ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Address 1:</th>
                    <td><?php echo $mainContact->clientAd_address1; ?></td>
                </tr>
                <?php if($mainContact->clientAd_address2): ?>
                <tr>
                    <th>Address 2:</th>
                    <td><?php echo $mainContact->clientAd_address2; ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->clientAd_address3): ?>
                <tr>
                    <th>Town/City:</th>
                    <td><?php echo $mainContact->clientAd_address3; ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Postcode:</th>
                    <td><?php echo $mainContact->clientAd_postcode; ?></td>
                </tr>
            </table>

             <table class="info_wrap ident">
                <caption>Description</caption>
                <tr>
                    <td class="description"><?php echo $this->site->getShortDesc(); ?></td>
                </tr>
            </table>

            <?php $mainContact = $this->site->getBillingAddress(); ?>

            <table class="info_wrap ident">
                <caption>Billing Address <span class="id_number">(<?php echo (isset($mainContact->clientAd_idAddress)) ? $mainContact->clientAd_idAddress : ''; ?>)</span></caption>
                <?php if (isset($mainContact->clientAd_idAddress)): ?>
                <?php if($mainContact->clientAd_addressName): ?>
                <tr>
                    <th>Address Name:</th>
                    <td><?php echo $mainContact->clientAd_addressName; ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Address 1:</th>
                    <td><?php echo $mainContact->clientAd_address1; ?></td>
                </tr>
                <?php if($mainContact->clientAd_address2): ?>
                <tr>
                    <th>Address 2:</th>
                    <td><?php echo $mainContact->clientAd_address2; ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->clientAd_address3): ?>
                <tr>
                    <th>Town/City:</th>
                    <td><?php echo $mainContact->clientAd_address3; ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Postcode:</th>
                    <td><?php echo $mainContact->clientAd_postcode; ?></td>
                </tr>
                <?php else: ?>
                <tr>
                    <td>No Billing address set.</td>
                </tr>
                <?php endif; ?>
            </table>

            <?php $mainContact = $this->site->getClientPersonnel(); ?>

            <table class="info_wrap ident">
                <caption>Main Liaison <span class="id_number">(<?php echo (isset($mainContact->clientPers_idClientPersonnel)) ? $mainContact->clientPers_idClientPersonnel : ''; ?>)</span></caption>
                <?php if(isset($mainContact->clientPers_idClientPersonnel)): ?>
                <tr>
                    <th>Name:</th>
                    <td><?php echo $mainContact->clientPers_name; ?></td>
                </tr>
                <?php if($mainContact->clientPers_position): ?>
                <tr>
                    <th>Position:</th>
                    <td><?php echo $mainContact->clientPers_position; ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->clientPers_phone): ?>
                <tr>
                    <th>Phone No:</th>
                    <td><?php echo $mainContact->clientPers_phone; ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->clientPers_email): ?>
                <tr>
                    <th>Email:</th>
                    <td><?php echo $mainContact->getMailto(); ?></td>
                </tr>
                <?php endif; ?>
                <?php else: ?>
                <tr>
                    <td>No contact details available</td>
                </tr>
                <?php endif; ?>
            </table>

            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'center'"
         class="siteEditTabs-BorderContainter">

        <div id="SiteTabs<?php echo $this->site->site_idSite; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Meters'">

                <!-- start site meter list -->
                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-id="meterStore<?php echo $this->site->site_idSite; ?>"
                      data-dojo-props="url:'site/data-store/type/siteMeters',requestMethod:'post'"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       id="meterGrid<?php echo $this->site->site_idSite; ?>"
                       data-dojo-props="
                        store: meterStore<?php echo $this->site->site_idSite; ?>,
                        structure: bba.Site.gridLayouts.meter,
                        query: { meter_idSite: <?php echo $this->site->site_idSite; ?> },
                        sortInfo: '-2',
                        noDataMessage : bba.gridMessage">
                    <script type="dojo/method" data-dojo-event="onRowClick">
                        bba.Meter.meterGridRowClick(this, {
                            meter_idSite : <?php echo $this->site->site_idSite; ?>
                        });
                    </script>
                </table>
            </div>
            <!-- end site meter list -->

            <!-- start site contract list -->
            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Contracts'">

                <span data-dojo-type="dojox.data.QueryReadStore"
                      data-dojo-props="url: 'contract/data-store/type/contract', requestMethod: 'post'"
                      data-dojo-id="siteContractStore<?php echo $this->site->site_idSite; ?>"></span>

                <table data-dojo-type="dojox.grid.DataGrid"
                       data-dojo-id="siteContractGrid<?php echo $this->site->site_idSite; ?>"
                       id="siteContractGrid<?php echo $this->site->site_idSite; ?>"
                       data-dojo-props="
                        store: siteContractStore<?php echo $this->site->site_idSite; ?>,
                        structure: bba.Contract.gridLayouts.contract,
                        query: { idSite: <?php echo $this->site->site_idSite; ?> },
                        sortInfo: '2',
                        noDataMessage : bba.gridMessage">
                        <?php if ($this->isAllowed('User')): ?>
                        <script type="dojo/method" data-dojo-event="onRowClick">
                            bba.Contract.contractGridRowClick(this);
                        </script>
                        <?php endif; ?>
                </table>
            </div>
            <!-- end site contract list -->
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <p class="tableHead-button">
                <button data-dojo-type="dijit.form.Button">
                    New Meter
                    <script type="dojo/method" data-dojo-event="onClick">
                        bba.Meter.newMeterButtonClick({
                            meter_idSite : <?php echo $this->site->site_idSite; ?>
                        });
                    </script>
                </button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>

