<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <div class="form_wrap zend_form site_edit ident alpha"
                 dojoType="dijit.form.Form"
                 id="edit-site-<?php echo $this->site->site_idSite; ?>">
                <h3>Site Details</h3>
                <div class="form_row">
                    <p class="label"><b>Client:</b></p>
                    <p>&nbsp;<?php echo $this->site->client_name; ?></p>
                </div>
                <?php if ($this->isAllowed('User')): ?>
                <button dojoType="dijit.form.Button"
                    type="submit"
                    name="edit-site-button-<?php echo $this->site->site_idSite; ?>"
                    value="submit">Edit Details</button>
                <?php endif; ?>
            </div>

            <div class="ident">
                <h3>Address</h3>
                <div>
                    <p><?php
                        $mainContact = $this->siteHelper($this->site->site_idSite)
                            ->getParentRow('siteAddress');

                        echo $this->formatAddress(array(
                            $mainContact->get('clientAd_addressName'),
                            $mainContact->get('clientAd_address1'),
                            $mainContact->get('clientAd_address2'),
                            $mainContact->get('clientAd_address3'),
                            $mainContact->get('clientAd_postcode')
                        ));
                    ?></p>
                </div>
            </div>

            <div class="ident">
                <h3>Billing Address</h3>
                <div>
                    <p><?php
                        $mainContact = $this->siteHelper($this->site->site_idSite)
                            ->getParentRow('siteAddressBill');

                        echo $this->formatAddress(array(
                            $mainContact->get('clientAd_addressName'),
                            $mainContact->get('clientAd_address1'),
                            $mainContact->get('clientAd_address2'),
                            $mainContact->get('clientAd_address3'),
                            $mainContact->get('clientAd_postcode')
                        ));
                    ?></p>
                </div>
            </div>

            <div class="ident">
                <h3>Contact</h3>
                <div>
                    <p><?php
                        $mainContact = $this->siteHelper($this->site->site_idSite)
                            ->getParentRow('siteClientContact');

                        echo $this->formatAddress(array(
                            $mainContact->get('clientCo_name'),
                            $mainContact->get('clientCo_position'),
                            $mainContact->get('clientCo_phone'),
                            $mainContact->get('clientCo_email')
                        ));
                    ?></p>
                </div>
            </div>

            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="siteEditTabs-BorderContainter">

        <div id="SiteTabs<?php echo $this->site->site_idSite; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Meters'">

                <span dojoType="dojox.data.QueryReadStore"
                     jsid="meterStore<?php echo $this->site->site_idSite; ?>"
                     url="/site/data-store/type/siteMeters"
                     requestMethod="post"></span>

                <table dojoType="bba.DataGrid"
                       jsId="meterGrid<?php echo $this->site->site_idSite; ?>"
                       store="meterStore<?php echo $this->site->site_idSite; ?>"
                       structure="bba.gridLayouts.siteMeter"
                       query="{ meter_idSite: <?php echo $this->site->site_idSite; ?> }"
                       queryParent="meter_idSite"
                       sortInfo="-3"
                       tabs="true"
                       tabTitleColumn="meter_numberMain">
                </table>
            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <p class="tableHead-button">
                <button dojoType="dijit.form.Button"
                        id="new-meter-button-<?php echo $this->site->site_idSite; ?>"
                        type="button">New Meter</button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>

