<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">
        <div class="tabHeading">

            <?php $mainContact = $this->siteHelper($this->site->site_idSite)
                    ->getParentRow('siteAddress'); ?>

            <table class="info_wrap">
                <caption>Site Details</caption>
                <tr>
                    <th>Client:</th>
                    <td><?php echo $this->site->client_name; ?></td>
                </tr>
                <?php if($mainContact->get('clientAd_addressName')): ?>
                <tr>
                    <th>Address Name:</th>
                    <td><?php echo $mainContact->get('clientAd_addressName'); ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Address 1:</th>
                    <td><?php echo $mainContact->get('clientAd_address1'); ?></td>
                </tr>
                <?php if($mainContact->get('clientAd_address2')): ?>
                <tr>
                    <th>Address 2:</th>
                    <td><?php echo $mainContact->get('clientAd_address2'); ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->get('clientAd_address3')): ?>
                <tr>
                    <th>Address 3:</th>
                    <td><?php echo $mainContact->get('clientAd_address3'); ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Postcode:</th>
                    <td><?php echo $mainContact->get('clientAd_postcode'); ?></td>
                </tr>
                <?php if ($this->isAllowed('User')): ?>
                <tr>
                    <td class="footer" colspan="2">
                        <div dojoType="dijit.form.Form"
                             id="edit-site-<?php echo $this->site->site_idSite; ?>">
                            <button dojoType="dijit.form.Button"
                                    type="submit"
                                    name="edit-site-button-<?php echo $this->site->site_idSite; ?>"
                                    value="submit">Edit Details</button>
                        </div>
                    </td>
                </tr>
                <?php endif; ?>
            </table>

            <?php $mainContact = $this->siteHelper($this->site->site_idSite)
                    ->getParentRow('siteAddressBill'); ?>

            <table class="info_wrap ident">
                <caption>Billing Address</caption>
                <?php if($mainContact->get('clientAd_addressName')): ?>
                <tr>
                    <th>Address Name:</th>
                    <td><?php echo $mainContact->get('clientAd_addressName'); ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Address 1:</th>
                    <td><?php echo $mainContact->get('clientAd_address1'); ?></td>
                </tr>
                <?php if($mainContact->get('clientAd_address2')): ?>
                <tr>
                    <th>Address 2:</th>
                    <td><?php echo $mainContact->get('clientAd_address2'); ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->get('clientAd_address3')): ?>
                <tr>
                    <th>Address 3:</th>
                    <td><?php echo $mainContact->get('clientAd_address3'); ?></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th>Postcode:</th>
                    <td><?php echo $mainContact->get('clientAd_postcode'); ?></td>
                </tr>
            </table>

            <?php $mainContact = $this->siteHelper($this->site->site_idSite)
                    ->getParentRow('siteClientContact'); ?>

            <table class="info_wrap ident">
                <caption>Contact</caption>
                <?php if($mainContact->get('clientCo_idClientContact')): ?>
                <tr>
                    <th>Name:</th>
                    <td><?php echo $mainContact->get('clientCo_name'); ?></td>
                </tr>
                <?php if($mainContact->get('clientCo_position')): ?>
                <tr>
                    <th>Position:</th>
                    <td><?php echo $mainContact->get('clientCo_position'); ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->get('clientCo_phone')): ?>
                <tr>
                    <th>Phone No:</th>
                    <td><?php echo $mainContact->get('clientCo_phone'); ?></td>
                </tr>
                <?php endif; ?>
                <?php if($mainContact->get('clientCo_email')): ?>
                <tr>
                    <th>Email:</th>
                    <td><?php echo $mainContact->get('clientCo_email'); ?></td>
                </tr>
                <?php endif; ?>
                <?php else: ?>
                <tr>
                    <td>No contact details available</td>
                </tr>
                <?php endif; ?>
            </table>

            <div class="clear"></div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.BorderContainer"
         data-dojo-props="design: 'headline', region: 'bottom', splitter: 'true'"
         class="siteEditTabs-BorderContainter">

        <div id="SiteTabs<?php echo $this->site->site_idSite; ?>"
             data-dojo-type="dijit.layout.TabContainer"
             data-dojo-props="region: 'center', tabStrip: 'true'"
             class="innerTabs">

            <div data-dojo-type="dijit.layout.ContentPane"
                 data-dojo-props="region: 'center', title: 'Meters'">

                <span dojoType="dojox.data.QueryReadStore"
                     jsid="meterStore<?php echo $this->site->site_idSite; ?>"
                     url="/site/data-store/type/siteMeters"
                     requestMethod="post"></span>

                <table dojoType="bba.DataGrid"
                       jsId="meterGrid<?php echo $this->site->site_idSite; ?>"
                       store="meterStore<?php echo $this->site->site_idSite; ?>"
                       structure="bba.gridLayouts.siteMeter"
                       query="{ meter_idSite: <?php echo $this->site->site_idSite; ?> }"
                       queryParent="meter_idSite"
                       sortInfo="-2"
                       tabs="true"
                       tabTitleColumn="meter_numberMain">
                </table>
            </div>
        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'bottom'"
         class="tableHeadPane">
        <div class="tableHead">
            <?php if ($this->isAllowed('User')): ?>
            <p class="tableHead-button">
                <button dojoType="dijit.form.Button"
                        id="new-meter-button-<?php echo $this->site->site_idSite; ?>"
                        type="button">New Meter</button>
            </p>
            <?php endif; ?>
        </div>
    </div>
</div>

