<?php $this->dojo()->requireModule('bba.Site'); ?>

<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">

        <div class="tabHeading">
            <?php
                $this->title = "BBA Sites";
                $this->headTitle($this->title);

                echo $this->siteSearchForm;
            ?>

            <div class="tableHead">
                <h2 class="tableHead-heading">Sites:</h2>
                <?php if ($this->isAllowed('User')): ?>
                <p class="tableHead-button">
                    <button dojoType="dijit.form.Button"
                            id="new-site-button"
                            type="button">New Site</button>
                </p>
                <?php endif; ?>
            </div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <span dojoType="dojox.data.QueryReadStore"
              jsid="siteStore"
              url="/site/data-store/type/site"
              requestMethod="post"></span>

        <table dojoType="bba.DataGrid"
               jsId="siteGrid"
               store="siteStore"
               query='<?php echo $this->search; ?>'
               sortInfo="2"
               search="true"
               tabs="true"
               tabTitleColumn="client_name">
            <thead>
                <tr>
                    <th field="site_idSite" width="50">Id</th>
                    <th field="client_name" width="300">Client</th>
                    <th field="client_desc" width="200">Description</th>
                    <th field="clientAd_addressName" width="200">Address Name</th>
                    <th field="clientAd_address1" width="200">Address 1</th>
                    <th field="clientAd_postcode" width="100">Postcode</th>
                    <th field="clientCo_name" width="100">Contact</th>
                    <th field="" width="auto"></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
