<?php
	$this->title = "BBA Sites";
	$this->headTitle($this->title);

    echo $this->siteSearchForm;
    /* @var $site Power_Model_Site */
?>
<table>
	<tr>
	<th>ID</th>
	<th>ClientID</th>
	<th>Address1</th>
	<th>Address2</th>
	<th>Address3</th>
	<th>PostCode</th>
	<th>&nbsp;</th>
	</tr>
<?php foreach($this->sites as $site): ?>
	<tr>
		<td><?php echo $this->escape($site->id);?></td>
		<td><?php //$client=$site->findParentRow(
			//'Application_Model_DbTable_Client',
			//'client_idClient');
		//echo $client['client_name'];?></td>
		<td><?php echo $this->escape($site->idAddress); ?></td>
		<td><?php //echo $this->escape($site->si_address2);?></td>
		<td><?php //echo $this->escape($site->si_address3);?></td>
		<td><?php //echo $this->escape($site->si_postcode);?></td>
		<td class="action">
			<a href="<?php echo $this->url(array(
                'controller'    => 'site',
                'action'        => 'edit',
                'siteId'        => $site->id
            ));?>" class="button">Edit</a>
			<a href="<?php echo $this->url(array(
                'controller'    =>'site',
                'action'        =>'delete',
                'siteId'        => $site->id
            ));?>" class="button">Delete</a>
		</td>
	</tr>
	<?php
//		$contracts=$meter->findManyToManyRowset(
//					'Application_Model_DbTable_Contract',  //to
  //                  'Application_Model_DbTable_MeterContract',  //via=intersectionTable
	//				'mecoMeter',	//get to intersectionTable
	//				'mecoContract');	//leave intersectionTable
	//	foreach($contracts as $contract) {
	//		echo "<tr><td></td><td>Contract: ".$contract['co_id']."</td></tr>";
	//	}
	?>
<?php endforeach; ?>
</table>

<p>
    <a href="<?php echo $this->url(array(
        'controller'    => 'site',
        'action'        => 'add'
    ), 'default', true);?>" class="button">Add new Site</a>
</p>
