<?php
	$this->title = "BBA Sites";
	$this->headTitle($this->title);

    echo $this->siteSearchForm;
    /* @var $site Power_Model_Site */
?>

<?php echo $this->partial('_table-head.phtml', array(
    'heading'   => 'Sites',
    'label'     => 'New Site',
    'location'  => $this->url(array(
        'controller'    => 'site',
        'action'        => 'add'
    ), 'default', true)
)); ?>

<script>
    dojo.addOnLoad(function(){
        dojo.connect(grid, "onRowClick", function(val){
            selectedIndex = grid.focus.rowIndex;
            selectedItem = grid.getItem(selectedIndex);
            //Not sure if this is the most efficient way but it worked for me
            selectedId = grid.store.getValue(selectedItem, "site_idSite");

            location.href = '/site/edit/siteId/' + selectedId;
        });
    });

</script>

<div dojotype="dojox.data.QueryReadStore"
     jsid="tableStore"
     url="/site/site-store"
     requestMethod="post"></div>

<table dojoType="dojox.grid.DataGrid"
       jsId="grid"
       store="tableStore"
       query="<?php echo $this->search; ?>"
       style="width:100%;height:500px;"
       autoWidth="false"
       autoHeight="false"
       rowSelector="0px"
       rowsPerPage="25"
       clientSort="true"
       noDataMessage="<span class='dojoxGridNoData'>No records found matching query</span>">
    <thead>
        <tr>
            <th field="site_idSite" width="50">Id</th>
            <th field="client_name" width="300">Client</th>
            <th field="client_desc" width="200">Description</th>
            <th field="clientAd_addressName" width="200">Address Name</th>
            <th field="clientAd_address1" width="200">Address 1</th>
            <th field="clientAd_postcode" width="100">Postcode</th>
            <th field="clientCo_name" width="100">Contact</th>
        </tr>
    </thead>
</table>

<?php
/*
if ($this->sites instanceof Zend_Paginator) {
    echo $this->paginationControl(
            $this->sites,
            'Sliding',
            '_paginate.phtml',
            array('params' => $this->search)
    );
}*/
?>
