<?php
$form = $this->{$this->formName};
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="siteForm"
     data-dojo-id="siteForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Site',
        execute: bba.Site.processSiteForm">
    <div class="dijitDialogPaneContentArea">

        <div class="dialog_title">

        </div>

        <div class="form_wrap">
            <div class="zend_form">

                <?php echo $form->site_idClient; ?>

                <?php echo $form->site_idAddress; ?>
                <div style="text-align:right; width:450px;">
                    <p>Note: To change the details of an address please
                    <br> edit via the Client &AMP; Client Address.</div>
      <!-- 3 lines above are temp fix until Issue #105 is implemented. -->
                <?php echo $form->site_idAddressBill; ?>

                <?php echo $form->site_idClientPersonnel; ?>

                <?php echo $form->site_desc; ?>

                <div class="dialog_footer_info">
                    <p class="required"> = required field</p>
                    <p class="warn">Cancel exits without saving</p>
                </div>
                <div class="clear"></div>

                <input data-dojo-type="dijit.form.TextBox"
                    type="hidden"
                    name="site_idSite"
                    id="site_idSite"
                    required="true"
                    value="<?php echo $form->site_idSite->getValue(); ?>" />

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return dijit.byId('siteForm').validate();}"
                        type="submit"
                        id="siteFormSubmitButton">Save</button>

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return bba.closeDialog(dijit.byId('siteForm'));}"
                        id="siteFormCancelButton">Cancel</button>
            </div>
        </div>
    </div>
</div>
<div data-dojo-id="siteFormStandby"
     data-dojo-type="dojox.widget.Standby"
     data-dojo-props="target:'siteForm', color: '#efefef', image: 'images/loader_lg.gif'"></div>
     