<?php $form = $this->{$this->formName}; ?>

<div class="form_wrap">
    <div class="zend_form">

        <?php echo $form->site_idClient; ?>

        <?php echo $form->site_idAddress; ?>

        <?php echo $form->site_idAddressBill; ?>

        <?php echo $form->site_idClientContact; ?>

        <input dojoType="dijit.form.TextBox"
               type="hidden"
               name="site_idSite"
               id="site_idSite"
               required="true"
               value="<?php echo $form->site_idSite->getValue(); ?>" />

        <button dojoType="dijit.form.Button"
                type="submit"
                id="siteFormSubmitButton"
                name="submit"
                value="Save">Save</button>

        <button dojoType="dijit.form.Button"
                type="button"
                id="siteFormCancelButton"
                name="cancel"
                value="Cancel">Cancel</button>
    </div>
</div>