<?php
$form = $this->{$this->formName};
$type = ($this->request()->getParam('type') == 'add') ? 'New' : 'Edit';
?>

<div data-dojo-type="dijit.Dialog"
     id="siteForm"
     data-dojo-id="siteForm"
     data-dojo-props="
        title:'<?php echo $type; ?> Site',
        execute: bba.Site.processSiteForm">
    <div class="dijitDialogPaneContentArea">

        <div class="form_wrap">
            <div class="zend_form">

                <?php echo $form->site_idClient; ?>

                <?php echo $form->site_idAddress; ?>
                
                <?php echo $form->site_idAddressBill; ?>

                <?php echo $form->site_idClientContact; ?>

                <?php echo $form->site_desc; ?>

                <input data-dojo-type="dijit.form.TextBox"
                    type="hidden"
                    name="site_idSite"
                    id="site_idSite"
                    required="true"
                    value="<?php echo $form->site_idSite->getValue(); ?>" />

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return dijit.byId('siteForm').validate();}"
                        type="submit"
                        id="siteFormSubmitButton">Save</button>

                <button data-dojo-type="dijit.form.Button"
                        data-dojo-props="onClick: function(){return bba.closeDialog(dijit.byId('siteForm'));}"
                        id="siteFormCancelButton">Cancel</button>
            </div>
        </div>
    </div>
</div>