<?php $this->dojo()->requireModule('bba/User', true); ?>
<div data-dojo-type="dijit.layout.BorderContainer"
     data-dojo-props="design: 'headline'"
     class="tabContainer">

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'top'">
        <div class="tabHeading">
            <?php
                $this->title = "BBA Users List";
                $this->headTitle($this->title);

                echo $this->userSearchForm;
                /* @var $client Power_Model_Client */
            ?>

            <div class="tableHead">
                <h2 class="tableHead-heading">Users:</h2>
                <?php if ($this->isAllowed('Admin')): ?>
                <p class="tableHead-button">
                    <button data-dojo-type="dijit.form.Button">
                        New User
                        <script type="dojo/method" data-dojo-event="onClick">
                            bba.User.newUserButtonClick();
                        </script>
                    </button>
                </p>
                <?php endif; ?>
            </div>

        </div>
    </div>

    <div data-dojo-type="dijit.layout.ContentPane"
         data-dojo-props="region: 'center'">

        <span data-dojo-type="dojox.data.QueryReadStore"
              data-dojo-props="url: 'user/user-store', requestMethod: 'post'"
              data-dojo-id="userStore"></span>

        <table data-dojo-type="dojox.grid.DataGrid"
            data-dojo-id="userGrid"
            id="userGrid"
            data-dojo-props='
                store: userStore,
                structure: bba.User.gridLayouts.user,
                query: <?php echo $this->search; ?>,
                sortInfo: "2",
                noDataMessage : bba.gridMessage'>
            <script type="dojo/method" data-dojo-event="onRowClick">
                bba.User.userGridRowClick(this);
            </script>
        </table>
    </div>
</div>